### ISSUE TITLE
Version mobile pour FirefoxOS

### ISSUE THREAD

**Issue by KanorUbu** [NextINpact/nxiv6#1]
Bonjour 
Est ce que ce serait possible de rajouter l'user agent de firefox os pour la version mobile ?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Firefox_OS

**Comment by o-schneider** [comment]
Hello,

Et de Firefox Android aussi. :)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Android_%28version_40_and_below%29

https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Android_%28version_41_and_above%29

**Comment by nahuelange** [comment]
+1 pour firefox android, la redirection des www. vers m. ne fonctionne pas… obligé de modifier l'url à la main…

**Comment by papci** [comment]
Hello,

la fonctionnalité est déjà dans notre backlog. Je laisse ouvert ce ticket afin pouvoir vous tenir au courant de sa mise en ligne.

**Comment by papci** [comment]
La redirection sur firefox mobile vers la version mobile est en ligne. merci pour votre patience ;)

**Comment by gentooboontoo** [comment]
@papci Merci à vous surtout :)
