### ISSUE TITLE
[LIDD] Impossible d'activer une vidéo

### ISSUE THREAD

**Issue by ttiot** [NextINpact/nxiv6#10]
Bonjour,

Je rencontre des difficultés récurrentes sur le site LIDD.
En effet, environ 80% du temps, je ne peux pas activer la module vidéo. Tout le JS à l'air planté (impossible d'ouvrir le menu connexion non plus). Je suis obligé de faire des refresh plusieurs fois pour arriver à lire une vidéo.
Je suis sous W10 64bits, Firefox 45.0.1
L'écran de mon ordinateur portable est tactile et j'ai également deux autres écrans (non tactiles) de connecter sur le portable. Je sais que le côté tactile pose des soucis.
Merci à vous

**Comment by papci** [comment]
Bonjour,

Il s'agit du bug tracker de Next INpact v6 et sa version mobile et non de  LIDD. merci :)
