### ISSUE TITLE
Crash d'onglet Chromium à l'ouverture de liens depuis votre site.

### ISSUE THREAD

**Issue by DVelbeck** [NextINpact/nxiv6#100]
Bonjour,

Cela fait un moment que je rencontre le problème suivant mais je n'avais jamais pris le temps de vous informer : un crash des pages de mon navigateur lorsque je clique sur n'importe quel lien qu'importe depuis la page de votre site que je consulte.

J'utilise Chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 17.3 (64-bit).

Exemple : Ce matin, j'étais sur votre article "Dans l'espace, la Chine continue ses essais avant la construction d'une station « permanente »". 

Puis j'ai cliqué sur "OpenLara : jouez à Tomb Raider depuis votre navigateur" en l'ouvrant dans un nouvel onglet. Sauf que le chargement du nouvel onglet fait crasher certains autres déjà chargés et qui pointent sur vos pages. Étonnement aussi celui du Comptoir de l'info (il m'arrive souvent d'accéder à vos articles depuis ce site). Ce qui donne le résultat que je vous ai joint en PJ.

Second exemple : Depuis la page de l'article "OpenLara : jouez à Tomb Raider depuis votre navigateur", j'ai fait ouvrir dans un nouvel onglet la page qui est résulte de votre lien "Nous contacter" afin d'accéder au formulaire dans lequel se trouve votre lien vers votre repo Github et vous faire part de ce bug. Rebelotte, crash.

Cordialement,
Daniel

![selection_003](https://cloud.githubusercontent.com/assets/10420265/25425928/7aed79be-2a65-11e7-9da6-3b91b3524798.png)

**Comment by papci** [comment]
Bonjour,

Cela semble plus lié à votre navigateur qu'au site en lui même, il vaudrait mieux vous tourner vers la communauté de ce dernier.
