### ISSUE TITLE
Compteur de commentaire avec +0 en page d'acceuil

### ISSUE THREAD

**Issue by rbtnk** [NextINpact/nxiv6#101]
Le compteur de commentaire sur une des actualités en page d’accueil affiche  "x+0" lorsqu'il n'y a pas de nouveau commentaires alors que sur les suivantes il affiche seulement "x".
C'est uniquement sur cet actualité peu importe sa position dans la page d’accueil.

J'utilise Vivaldi 1.9.818.40 (64 bits) sous Windows 7 pro SP1 64bits. 
Voir la configuration de ma page d’accueil et le problème dans l'image ci-dessous (prise avec un compte abonné et connecté).

![nierr](https://cloud.githubusercontent.com/assets/28106312/25491963/dc0a5d04-2b71-11e7-9045-c4bdb8b3bd3a.PNG)

**Comment by rbtnk** [comment]
Ceci est également reproductible sous Firefox 50.1.0
Cela se produit sur certaines actualités mais pas sur toutes.
Un autre exemple "QNAP lance ses NAS TS-x53B avec emplacement PCIe et écran OLED, dès 599,95 €" du 25/04 à 1400.

**Comment by papci** [comment]
C'est tout à fait normal, l'indicateur +xx n'est affiché uniquement après avoir déjà lu les commentaires associés à l'actu.
