### ISSUE TITLE
Désactiver le "une erreur ?"

### ISSUE THREAD

**Issue by Alwaysin** [NextINpact/nxiv6#102]
Ce menu contextuel qui apparaît lorsque l'on sélectionne du texte est très pénible.
Je sélectionne notamment pour m'aider à lire le texte, et ça cache souvent d'autres parties de phrases, mais aussi pour faire des recherches. Or, lorsque l'on sélectionne un mot, on ne peut maintenant plus avoir le "rechercher avec google" sous Chrome par exemple.

Est-il possible d'avoir au moins la possibilité de désactiver ce menu ? Ou alors le faire apparaître à un endroit non gênant et rétablir la possibilité de recherche rapide.

**Comment by rphlmr** [comment]
Remonter la bulle serait pas mal aussi car elle rend difficile l'accès au menu contextuel sur la sélection. Quand on clic droit sur le texte sélectionné, c'est surtout sur la bulle qu'on le fait car elle est trop proche.

**Comment by Alwaysin** [comment]
Parfait, option désactivée, merci !
