### ISSUE TITLE
Les touches j et k pour passer à l'article suivant/précédent ne fonctionnent plus

### ISSUE THREAD

**Issue by MoiMemePerso** [NextINpact/nxiv6#103]
Avant la MAJ, on pouvait passer facilement d'un article à l'autre grâce aux touches J et K, permettant d'aller à l'article suivant ou précédent. Depuis la MAJ, cette fonction n'est plus active.
Pour info, la touche R qui permet d'aller à un article au hasard est quant à elle toujours fonctionnelle.

**Comment by papci** [comment]
Le bug est identifié et sera fixé lors du déploiement prochain, je fermerai le ticket quand ça sera effectif ;)

**Comment by papci** [comment]
c'est mis en prod ;)

**Comment by MoiMemePerso** [comment]
Yay !
Merci ^^

De : Pierre-Alain David [mailto:notifications@github.com]
Envoyé : jeudi 19 octobre 2017 09:40
À : NextINpact/nxiv6 <nxiv6@noreply.github.com>
Cc : MoiMemePerso <r.ricou@outlook.fr>; Author <author@noreply.github.com>
Objet : Re: [NextINpact/nxiv6] Les touches j et k pour passer à l'article suivant/précédent ne fonctionnent plus (#103)


c'est mis en prod ;)
