### ISSUE TITLE
Le formulaire de contact n'affiche pas les champs email et type de demande

### ISSUE THREAD

**Issue by maxbritto** [NextINpact/nxiv6#104]
Sur cette page : https://www.nextinpact.com/a-propos.htm#nouscontacter_section
Les champs pour saisir l'email et le type de demande ne sont pas affichés dans Chrome, Safari et Safari TP.
Ils sont visibles sur Firefox par contre.

**Comment by papci** [comment]
Il s'agit d'un problème lié a l'utilisation d'Adblock, le désactiver devrait suffir (éventuellement, tu peux signaler le bug à la communauté Easylist : https://forums.lanik.us/viewforum.php?f=91)

**Comment by maxbritto** [comment]
Ah mince je n'y avais pas pensé :(
Dans tous les cas j'ai réussi à envoyer mon message via Firefox, c'était surtout pour vous prévenir.
