### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by nbelie** [NextINpact/nxiv6#105]
Lorsqu'AdBlocks est activé sur le site, le formulaire de contact ne s'affiche pas correctement : 
- La drop down list "type de la demande" n'est pas disponible - seulement le header
- le champ "votre adresse mail" : n'est pas disponible - seulement le header
Une fois l'adblocker désactiver et la page rafraîchie : plus aucun problème

**Comment by papci** [comment]
Il s'agit effectivement d'un problème lié aux bloqueurs de publicité. Je vous invite à vous raprocher de la communauté de la liste FR (https://forums.lanik.us/viewforum.php?f=9) afin qu'ils puissent corriger le souci.
