### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by aglp** [NextINpact/nxiv6#109]
Il semble y avoir un problème avec votre formulaire de contact : 
https://www.nextinpact.com/a-propos.htm#nouscontacter_section

Les champs "Type de la demande" et "Votre adresse email" ne peuvent pas être renseignés (testé sous Chrome et Firefox)
![nextinpact](https://cloud.githubusercontent.com/assets/28596207/26655673/0f2c17c2-465c-11e7-8b9b-cdcf55b33003.PNG)

**Comment by papci** [comment]
Bonjour,
Il s'agit d'un souci à l'utilisation d'adblock, le désactiver règle le souci.
