### ISSUE TITLE
Problème de mise en page version mobile

### ISSUE THREAD

**Issue by Korhm** [NextINpact/nxiv6#11]
Bonjour,

Il y a un problème de mise en page sur la version mobile du site. Du contenu déborde sur la droite de l'écran et n'est donc pas visible

Constaté sur un iPhone 5, sur la page résumé des bons plans de la semaine

**Comment by VooDooS** [comment]
Même phénomène depuis quelques temps de mon côté, sous chrome sur Android. 
Pas de scrolling horizontal possible, alors que les titres et sous-titres des news dépassent sur la droite en vue liste. Ils semble que tous les autres éléments soient positionnés correctement.

**Comment by VooDooS** [comment]
Même phénomène depuis quelques temps de mon côté, sous chrome sur Android. 
Pas de scrolling horizontal possible, alors que les titres et sous-titres des news dépassent sur la droite en vue liste. Ils semble que tous les autres éléments soient positionnés correctement.

**Comment by VooDooS** [comment]
Même problème de mon côté depuis plusieurs jours.
Chrome sur Android 6.

Problème présent sur la liste des actualités, les titres et sous-titres dépassent, mais aucun scrolling horizontal n'est possible. Le autres éléments semblent correctement positionnés.

![screenshot_20160405-112450](https://cloud.githubusercontent.com/assets/5031221/14277641/622a3384-fb24-11e5-8413-4e0355fab311.png)

**Comment by oldchap32** [comment]
même problème sur android 5.1.1, chrome et firefox

**Comment by papci** [comment]
Merci pour votre intervention à tous, la correction est en cours.

**Comment by papci** [comment]
Corrigé et live
