### ISSUE TITLE
Differencier les tweets de news et de news passant en accès libre

### ISSUE THREAD

**Issue by Socolin** [NextINpact/nxiv6#111]
Serait-il possible d'avoir un moyen d'identifier sur le twitter les tweets a propos d'une nouvelle actu des tweets partageant une news qui passe en accès libre, sans avoir besoin d'ouvrir la news et de scroll tout en bas pour vérifier la date.
Ou de faire un compte twitter qui publierais seulement les nouveautés ?

**Comment by papci** [comment]
Merci pour la remontée, l'équipe rédactionnelle est informée et fera le nécessaire rapidement.
