### ISSUE TITLE
Problème de redirection de liens

### ISSUE THREAD

**Issue by Mangwo** [NextINpact/nxiv6#113]
Bonjour,
Je ne suis pas habituer avec ces manipulations alors excusez mes éventuelles maladresses, svp.
Lorsque je clique sur un lien qui se rapporte à un pub pour "RueduCommerce", je tombe sur une page d'erreur: https://ui.zanox-affiliate.de/bin/z_in_frm.dll#2406435037637522589
Mais en cliquant sur le bouton "Avancé" de cette page, il donne : ui.zanox-affiliate.de uses an invalid security certificate. The certificate expired on 20 septembre 2014 à 01:59. The current time is 21 juin 2017 à 17:37. Error code: SEC_ERROR_EXPIRED_CERTIFICATE.
On a la possibilité d'ajouter une exception. Serait-elle sans danger?
Firefox 54.0(64bits) NoScript 5.0.5, ABP, Ubuntu 16.04 LTS.
Cordialement,

PS- Je vous joins les captures que j'ai pu faire...
![capture du 2017-06-21 17-02-54](https://user-images.githubusercontent.com/29607072/27393928-d7a8ff9a-56aa-11e7-87aa-5a216aa41b74.png)
![capture du 2017-06-21 17-03-34](https://user-images.githubusercontent.com/29607072/27393950-ed174314-56aa-11e7-9954-db940135c6eb.png)

**Comment by papci** [comment]
Bonjour,

Le problème est-il encore d'actualité ?
