### ISSUE TITLE
Impossible de se connecté sur telephone depuis les liens twitter

### ISSUE THREAD

**Issue by Socolin** [NextINpact/nxiv6#114]
Bonjour,

Depuis quelques jours les lien des news posté sur twitter, depuis mon telephone (Nexus 5X / android) renvoie vers un nom de domaine `amp.nextinpact.com` different du `m.nextinpact.com` et il est impossible de se connecté depuis ce sous domaine, il y a seulement un bouton "Abonnez-vous" mais impossible de se connecter.

**Comment by papci** [comment]
Bonjour,

Dans certaines configurations, la redirection vers la version AMP est automatique et ne dépends pas entièrement de nous. Nous allons étudier le cas et prendre une décision prochainement d'ici peu.

**Comment by Socolin** [comment]
Bonjour,

Any news ? impossible de consulter le site depuis le flux google et je suis obliger de changer l'url a chaque fois depuis twitter c'est assez pénible.

Si vous pouvez au moins mettre le bouton pour s'identifier sur ce sous domaine... il y a seulement la redirection vers l'abonnement donc sur telephone je ne sais meme pas comment m'identifier.

Si la version amp n'est pas fini pourquoi la laisser active ?
