### ISSUE TITLE
Envoi de commentaire depuis mobile

### ISSUE THREAD

**Issue by mickaelbl** [NextINpact/nxiv6#116]
Bonjour,

Depuis quelques temps, il est impossible d'envoyer un commentaire depuis le site mobile.

Testé avec Chrome ou Firefox depuis un téléphone Android
Testé aussi sur un ordi en forçant le passage du site en version mobile.

Le bouton d'envoie (petite bulle) s'active dès que le entre du texte dans le champ prévu mais l'envoi ne se fait pas.

**Comment by bghenne** [comment]
Je rencontre exactement le même problème.

**Comment by bghenne** [comment]
Plus d'informations : 

Request URL:https://m.nextinpact.com/comment/send
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:104.25.248.21:443
Referrer Policy:no-referrer-when-downgrade

Erreur 500 lorsque le commentaire est posté en Ajax.

**Comment by papci** [comment]
Bonjour,

Pourriez-vous me donner un peu plus d'info : 

- cela se produit-il systématiquement ?
- Sinon : sur quelle actu vous rencontrez le problème ?

merci ;)

**Comment by mickaelbl** [comment]
Bonjour,
Quelque soit la news, impossible de poster.

L'icône d'envoi s'active bien dès qu'il y a du texte et se grise dès que l'on appuie dessus pour envoyer.

**Comment by Leepic** [comment]
Bonsoir,

J'ai rencontré ce souci aussi plusieurs fois sur [cet article](https://m.nextinpact.com/news/105277-skred-skyrock-lance-sa-messagerie-libre-et-securisee-mais-peu-trop-fermee.htm).

C'est permanent pour ma part.

Je confirme l'erreur que signale @bghenne, voici l'en-têtes : 
```
URL de la requête : https://m.nextinpact.com/comment/send
Méthode de la requête : POST
Adresse distante : 104.25.248.21:443
Code d’état : 500 Internal Server Error
Version : HTTP/2.0
```

Ma requête : 

```
Host: m.nextinpact.com
User-Agent: Mozilla/5.0 (Android 4.1.2; Mobile; rv:58.0) Gecko/58.0 Firefox/58.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: https://m.nextinpact.com/news/105390-sur-ios-attention-aux-fausses-fenetres-didentification-compte-apple.htm
Content-Length: 73
DNT: 1
Connection: keep-alive
```
J'ai omis l'en-tête « Cookie » volontairement.

La réponse : 

```
date: Wed, 11 Oct 2017 21:21:00 GMT
content-type: text/html; charset=utf-8
cache-control: private, s-maxage=0
x-aspnetmvc-version: 5.2
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET
server: cloudflare-nginx
cf-ray: 3ac4ddd5fcd96932-CDG
X-Firefox-Spdy: h2
```

Besoin de plus d'informations pour le debug ?

**Comment by papci** [comment]
Un correctif a été appliqué ce matin, est-ce que vous pouvez me confirmer que tout est bon pour vous ?

**Comment by mickaelbl** [comment]
Non toujours le même souci pour ma part

**Comment by mickaelbl** [comment]
Correction,
Ça  remarche !
