### ISSUE TITLE
Bug affichage date sur l'espace abonnement

### ISSUE THREAD

**Issue by Elioty** [NextINpact/nxiv6#117]
La page https://compte.nextinpact.com/gestion/abonnement m'indique :
> Votre abonnement expirera le 01/10/2017 à 12:55
> Durée maximale d'engagement atteinte.
> Vous pourrez prolonger votre abonnement à partir du 01/01/0001

La date affichée à la fin est clairement erronée !!!

**Comment by papci** [comment]
Il s'agit d'un problème lié a ton compte : il vaut mieux écrire au support dans ce cas la ;)
