### ISSUE TITLE
Exclure les "briefs" du flux RSS

### ISSUE THREAD

**Issue by kriks57** [NextINpact/nxiv6#120]
Bonjour,

j'utilise beaucoup NXI depuis un lecteur RSS.
Est-il possible d'exclure les éléments individuels du brief, et de ne laisser que la news du brief ?
Ça fait un peu doublon, et ça génère beaucoup d'entrées dans le lecteur RSS :)

merci!

**Comment by papci** [comment]
Bonjour,

Tu trouvera certainement ton bonheur sur la page suivante : https://www.nextinpact.com/rss-social

Bonne journée.

**Comment by kriks57** [comment]
merci, j'avais loupé les petits liens :D 👍

**Comment by Marsup** [comment]
@papci comment on fait ça avec le flux complet du premium ?

**Comment by jereze** [comment]
Bonjour, 

Pour ma part, je préfère au contraire avoir les briefs individuels dans le flux complet (sinon je les rate complètement). Ce n'est pas le cas actuellement.

Pour la news annonçant les briefs, il n'y a pas le contenu des briefs.

![capture d ecran 2017-10-05 a 11 20 25](https://user-images.githubusercontent.com/4386500/31219984-53543666-a9bf-11e7-9519-22d8d83ee94c.png)
