### ISSUE TITLE
Erreur 500 au chargement des commentaires - version mobile

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/nxiv6#121]
Hello,

Le chargement des commentaires sur la version mobile produit une erreur 500 systématiquement.

Exemple : 
https://m.nextinpact.com/news/105303-le-recap-bons-plans-moment-semaine-39.htm
![image](https://user-images.githubusercontent.com/6187125/31045233-4ccf6e8e-a5df-11e7-8a8a-21067af894ba.png)
`
POST XHR https://m.nextinpact.com/comment/ [HTTP/2.0 500 Internal Server Error 214 ms]
`
![image](https://user-images.githubusercontent.com/6187125/31045243-8f9b818a-a5df-11e7-9c5a-0de336e2e93d.png)
![image](https://user-images.githubusercontent.com/6187125/31045246-9ef4eb58-a5df-11e7-876e-f8ddded2b128.png)
![image](https://user-images.githubusercontent.com/6187125/31045247-a6fe7378-a5df-11e7-96a5-0b46e31e3356.png)
![image](https://user-images.githubusercontent.com/6187125/31045251-b434a346-a5df-11e7-9689-dd63f2bfa4a7.png)
![image](https://user-images.githubusercontent.com/6187125/31045253-bee3b6ba-a5df-11e7-950c-aab0a483687d.png)

Bon courage :)

**Comment by papci** [comment]
Merci ;)

**Comment by papci** [comment]
Un fix a  été appliqué ce matin pour les utilisateurs non connectés. Dis moi si ça règle le souci de ton coté.

**Comment by AnaelMobilia** [comment]
Tout est ok à mon niveau, merci !
