### ISSUE TITLE
Erreur de chargement des commentaires du brief

### ISSUE THREAD

**Issue by AnaelMobilia** [NextINpact/nxiv6#122]
Hello,

Affichage du brief sur le site mobile.
Clic sur une icône commentaire (voir url en bas de la capture d'écran)
=> Message d'erreur...

![image](https://user-images.githubusercontent.com/6187125/31146815-124a82ac-a888-11e7-986d-9bb939ccc014.png)

Bon courage !
Anael

**Comment by papci** [comment]
Salut,

On est au courant du problème, un correctif arrive bientôt !

**Comment by papci** [comment]
c'est en prod (depuis quelque temps maintenant).
