### ISSUE TITLE
Problème de rechargement de page sur Mac

### ISSUE THREAD

**Issue by vincentnock** [NextINpact/nxiv6#123]
La touche R semble activer une feature d'ouverture d'article aléatoire.
Seulement, les macs rafraîchissent les pages avec Cmd+R, ce qui active la fonction en même temps que le rechargement de la page, et cause un changement de page non voulu.

**Comment by dgoujard** [comment]
Je confirme le bug c'est assez gênant :sweat_smile:

**Comment by papci** [comment]
On va retirer la fonctionnalité d'ici peu, merci de votre patience

**Comment by papci** [comment]
c'est mis en prod, merci à vous.
