### ISSUE TITLE
Impossible de vous contacter !

### ISSUE THREAD

**Issue by GB59** [NextINpact/nxiv6#124]
La page https://www.nextinpact.com/a-propos.htm#nouscontacter_section
ne permet pas de transmettre de message. Le bouton "envoyer" semble inactif.
*testé avec FF 56.0 (64bits) et Chrome Version 61.0.3163.100 (Build officiel) (64 bits)

**Comment by papci** [comment]
Bonjour,

Il s'agit d'un problème lié a votre bloqueur de publicité, le désactiver règle le souci.
