### ISSUE TITLE
Problème d'affichage sur mobile (bons plans du moment)

### ISSUE THREAD

**Issue by mickaelbl** [NextINpact/nxiv6#13]
Bonjour,

Petit bug d'affichage que je croise depuis un certain temps,

Sur la version mobile du site et uniquement sur les pages des Bons plans du moment,
Les titres des articles en bon plan sont tronqués, en portrait uniquement, en paysage, aucun soucis.

Que cela soit sur Chrome (normal ou beta) ou sur Firefox.

Cordialement,
Mickaël

![screenshot_20160418-141200](https://cloud.githubusercontent.com/assets/18530881/14603791/16cc6514-0570-11e6-9802-7f19f8509c4b.png)

**Comment by Hipparchia** [comment]
Problème non constaté sur Chrome ou Firefox (à jour et avec un Ghostery sur FF).
Je suis sur un HTC One M7, Android 5.0.2
![screenshot_2016-04-18-15-20-10](https://cloud.githubusercontent.com/assets/18531935/14605830/be565e20-057a-11e6-9639-f57ba003209d.png)
![screenshot_2016-04-18-15-18-53](https://cloud.githubusercontent.com/assets/18531935/14605829/be5448b0-057a-11e6-98ce-148aee295c03.png)

**Comment by papci** [comment]
Le problème était bien présent (sur les actus récap' bons plans), mais c'est corrigé ;)
