### ISSUE TITLE
Site mobile : nombre de commentaire par actu non pris en compte

### ISSUE THREAD

**Issue by Leepic** [NextINpact/nxiv6#130]
Bonsoir,

Sur [le site mobile](https://m.nextinpact.com), mes préférences sur le nombre de commentaires par actu n'est pas pris en compte. Peut importe l'actualité. C'est en revanche fonctionnel sur le site « classique ».

J'ai tenté de me déconnecter/reconnecter, changer le nombre de commentaire (sans erreur lors de la sauvegarde) mais à chaque fois maximum 10 commentaires par page.

J'utilise Firefox Mobile v58 sous Android 4.1.2, constaté aussi avec le mode mobile sur Firefox Desktop v58 (CTRL + SHIFT + M).

De quoi avez-vous besoin pour avancer ?

Bonne soirée

**Comment by papci** [comment]
Merci 👍

**Comment by papci** [comment]
C'est corrigé, bonne journée !
