### ISSUE TITLE
Utilisation des espaces insécables

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nxiv6#132]
En Français, '«' est suivit d'un espace insécable, ainsi que '?' et '»' en sont précédé d'un (je recommande la lecture de https://fr.wikipedia.org/wiki/Espace_insécable pour voir tous les caractères qui doivent être précédé ou suivit d'un espace insécable)

Le problème apparaît par exemple deux fois dans https://www.nextinpact.com/lebrief/edition-46.htm, dans la news sur Google Assistant, et dans la news sur VESA.

Corriger cela n'est pas excessivement dur, mais améliorerait grandement la lecture.

**Comment by papci** [comment]
Bonjour,

Pour toute suggestion relative au contenu, il vaut mieux contacter directement la rédaction ;)

**Comment by Cqoicebordel** [comment]
Il ne s'agit pas d'une suggestion relative au contenu, il s'agit d'ajouter un script replacant tous les " ?" par "espaceinsecable?" et pareil pour tous les autres signes de ponctuation affecté :)

Notons au passage que cette demande avait été corrigé dans #40, puis au fur du temps, c'est revenu sous forme de regression... ;)

**Comment by Cqoicebordel** [comment]
@papci, tu ne sembles pas lire les commentaires des bugs fermés (pareil dans #40), du coup, je me permets de te pinger juste au cas où ;)
