### ISSUE TITLE
Les versions AMP des pages du site mobile ne reconnaissent pas les abonnés

### ISSUE THREAD

**Issue by CyberSinh** [NextINpact/nxiv6#136]
Bonjour,

Je suis le flux des articles NextINpact sur Twitter (appli Android).

Lorsque je clique sur un lien, Twitter m'ouvre une page avec le contenu de l'article. La version AMP de la page est par défaut ouverte (le lien commence par "amp."). Sauf que j'ai droit à un gentil message "vous avez lu XX% de l'article, abonnez-vous pour lire le reste..." alors que je suis pourtant bien abonné et bien connecté.

La seule solution trouvé est de sélectionner "ouvrir dans Chrome" (mobile) afin d'avoir accès à la barre d'adresse et de remplacer "amp." par "m.". Et là, je suis bien reconnu comme abonné et l'article m'est bien affiché dans son intégralité. Mais comme la manip est quand même fastidieuse, il serait bon que les versions AMP du site reconnaissent bien les abonnés des anonymes (problème d'accès aux cookies ?) ou que la version mobile classique (non AMP) soit sélectionnée par défaut.

Merci.

**Comment by papci** [comment]
Bonjour,

Merci pour la remontée. La version AMP va être retirée sous peu, ce qui devrait résoudre le problème ;)
