### ISSUE TITLE
Thème Next Inpact Sombre -> Page de contact

### ISSUE THREAD

**Issue by NSicaud** [NextINpact/nxiv6#137]
Bonjour,

J'ai remarqué un bug CSS sur la page de contact (https://www.nextinpact.com/a-propos.htm#nouscontacter_section). Avec le thème NextInpact Classique Sombre, la liste déroulante du champ type de demande à un problème. Le texte est noir ce qui rend la lecture impossible. Je suis obligé de passer la souris dessus pour qu'il s'éclaircisse. Ca pourraît être cool d'inverser les couleurs pour ce thème dans la liste déroulante.

Bonne journée ;)

Mon support : http://supportdetails.net/Z03VAWA0

**Comment by darkweizer** [comment]
À clôturer non? En mode sombre, la liste est bien blanche pour moi maintenant =).

**Comment by papci** [comment]
Hellon oui un fix a été appliqué ce jour ;)
