### ISSUE TITLE
Le Brief + Listes à puces + Theme sombre

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nxiv6#138]
![image](https://user-images.githubusercontent.com/2286246/33957869-25990962-e043-11e7-9702-2a833f54ba89.png)

L'image suffit pour comprendre le problème :)

Testé sous Chromium, Vivaldi et Firefox, sous Linux.

**Comment by Cqoicebordel** [comment]
Je ne vais pas ouvrir un nouveau bug pour ça (sauf si c'est demandé), mais le même genre de problème, avec le thème sombre, apparaît sur les images : 
![image](https://user-images.githubusercontent.com/2286246/34070518-1735c7bc-e268-11e7-9095-e13d3f92d067.png)
(dans l'article https://www.nextinpact.com/news/105715-la-hadopi-fait-son-bilan-sept-ans-riposte-graduee.htm

**Comment by papci** [comment]
Hello,

Pour ton premier ticket, c'est résolu, merci à toi ;)
Pour le deuxieme, je vais voir avec la rédac : c'est simplement du à l'utilisation d'un png transparent :)
