### ISSUE TITLE
Positionnement de la barre latérale sur les fenteres non maximisées.

### ISSUE THREAD

**Issue by UtherII** [NextINpact/nxiv6#14]
Si la fenêtre n'est pas maximisée, la barre de droite est généralement en partie en dehors de la page, Il faut scroller horizontalement pour la consulter. Ce qui n'est pas pratique.
![bug](https://cloud.githubusercontent.com/assets/4951278/14605757/667e1b02-057a-11e6-8fb5-d460badc5920.png)

Le dimensionnement des zones principales de l'interface semble prévu en fonction de la taille totale de l'écran, au lieu de la taille réelle de la fenêtre. 

Vu sur Firefox et Chromium version bureau.

**Comment by papci** [comment]
Effectivement le site est pensé pour une surface d'affichage d'au moins 1280px de large. Il n'y aura pas de retouches sur ce point dans l'immédiat. Je note cependant afin de voir si on ne peut pas proposer d'améliorations sur ce point dans les prochaines versions de NXi.
