### ISSUE TITLE
Changement de mois datepicker #LeBrief

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#140]
Bonjour,

À chaque fois que je clique sur le mois pour le changer, le datepicker se ferme !
[https://image.noelshack.com/fichiers/2017/51/2/1513640628-datepicker-nx.gif](https://image.noelshack.com/fichiers/2017/51/2/1513640628-datepicker-nx.gif)

Cordialement.

Edit : [http://supportdetails.net/CO66B2X3](http://supportdetails.net/CO66B2X3)

**Comment by darkweizer** [comment]
Là aussi le correctif a dû être appliqué car cela fonctionne maintenant =).

Par contre, il retourne automatique au mois actuel.  C'est-à-dire si je vais voir #LeBrief du 4 octobre (au hasard) et que je clique pour ouvrir le datepicker, j'ai le mois de janvier qui apparait et pas celui d'octobre.
Pour le moment ça va, il n'y a que 3-4 mois, mais ça peut vite être embêtant quand on aura des années à remonté (même si un choix de l'année pourra être ajouté à ce moment là).
Vous fermez celui-ci et j'ouvre un autre ticket ou vous le prenez en charge via ce ticket ?! =).

Cordialement.

P.S.: Meilleurs vœux à vous !

**Comment by papci** [comment]
Bonjour,

Meilleur voeux également. Le retour au mois courant est voulu pour le moment.

**Comment by darkweizer** [comment]
D'accord =).
