### ISSUE TITLE
Class pastille-type au dessus de la selection du mode d'affichage

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#141]
Bonjour,

Les pastilles «Accès libre» et «En bref» ne sont pas cachées par l'encart du mode d'affichage.
[https://image.noelshack.com/fichiers/2017/51/2/1513644119-capture.png](https://image.noelshack.com/fichiers/2017/51/2/1513644119-capture.png)

Cordialement.

**Comment by papci** [comment]
c'est corrigé ;)
