### ISSUE TITLE
L'encart du mode d'affichage n'apparait plus

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#142]
Bonjour,

Procédure : 

1. Être dans n'importe quel mode d'affichage et choisir «Vignettes : le meilleur de l'actualité».

2. Essayer d'ouvrir l'encart du mode d'affichage ->n'apparait plus.

3. Si on recharge la page, l'encart réapparait par contre.

[https://image.noelshack.com/fichiers/2017/51/2/1513645131-mode-affichage-nx-1.gif](https://image.noelshack.com/fichiers/2017/51/2/1513645131-mode-affichage-nx-1.gif)
[https://image.noelshack.com/fichiers/2017/51/2/1513645127-mode-affichage-nx-2.gif](https://image.noelshack.com/fichiers/2017/51/2/1513645127-mode-affichage-nx-2.gif)

Cordialement.

**Comment by darkweizer** [comment]
Je ne sais pas si un correctif a été effectué mais ça ne me le fait plus ! =)

**Comment by papci** [comment]
salut, c'est corrigé ;)
