### ISSUE TITLE
box-shadow de msg_add_citation déborde sur #global_comment dans les commentaires

### ISSUE THREAD

**Issue by dlicois** [NextINpact/nxiv6#143]
Bonjour,

Dans la liste des commentaires d'une news, une ombre apparaît à gauche de chaque commentaire au millieu (vertical).
https://screenshots.firefox.com/7dH9GJS6fP4YY0s3/www.nextinpact.com (firefox 57 linux ).

C'est la box-shadow du bloc .msg_add_citation qui apparaît alors que celui-ci est encore caché.

Il faut peut-être mieux la cacher ou n'appliquer l'ombre que lors de l'animation.

Cordialement.

**Comment by papci** [comment]
c'est corrigé ;)
