### ISSUE TITLE
[Options d'affichage] Augmenter les tailles de police et hauteurs de ligne

### ISSUE THREAD

**Issue by gitomato** [NextINpact/nxiv6#144]
Il est actuellement possible de choisir trois tailles de police dans les options : `13px`, `14px`, `15px`.
Je souhaiterais pouvoir choisir une taille bien plus grande, avec un line-height adapté.
`18px` me paraît déjà plus agréable (faites le test).

En comparaison, un article sur Medium utilise par défaut `21px` et un line-height généreux.
https://medium.com/mule-design/design-in-the-age-of-anxiety-7a26f52d7aa1

On peut aborder cela sous l'angle du nombre de caractères idéal sur une ligne : 45 à 75 caractères selon l'article suivant : https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/
(en passant, le site utilise la formule `font-size: calc(18px + .25vw);`.
Sur un article choisi au hasard sur NextINpact, je dénombre 120 caractères sur une ligne.

Mes yeux vous remercient !

**Comment by papci** [comment]
Bonjour,

Ce n'est pas a l'ordre du jour, mais lors d'une prochaine version de NXi, il y aura certainement un changement dans la gestion des polices.
