### ISSUE TITLE
Image sur thème sombre

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#146]
Bonjour,

Sur l'actu [Hadopi : les chiffres de la riposte graduée en Open Data suite à une demande CADA](https://www.nextinpact.com/news/105905-hadopi-chiffres-riposte-graduee-en-open-data-suite-a-demande-cada.htm), avec le thème sombre, le texte sur l'image est illisible ;). [petit screen](https://image.noelshack.com/fichiers/2018/01/3/1514975262-graphique-sur-fond-noir.png)

Cordialement.

**Comment by papci** [comment]
Merci pour le rapport, c'est plus un problème coté rédac, je leur remonte :)

**Comment by darkweizer** [comment]
Ah, c'est côté rédac ^^'. D'accord, je le saurai pour les prochaines fois =).
