### ISSUE TITLE
Recherche non fonctionelle

### ISSUE THREAD

**Issue by ohhopi** [NextINpact/nxiv6#147]
Je n'arrive pas à utiliser la recherche. La page indique une "erreur dans la requête". (Testé sur Chrome et Edge)

[Voici mon URL de recherche](https://www.nextinpact.com/recherche?ListTypeContent.actus_view=true&ListTypeContent.dossiers_view=true&ListTypeContent.bonsplans_view=true&ListTypeContent.archives_view=true&_search=NAS)

Cela se produit aussi sur d'autres mots clés, que je sois connecté ou non.

![https://my.mixtape.moe/evnujz.png](https://my.mixtape.moe/evnujz.png)

**Comment by papci** [comment]
Bonjour,

On est au courant, il s'agit d'un probleme du coté de notre infrastructure. Le problème est en cours de correction.
