### ISSUE TITLE
Encart CES mal affiché

### ISSUE THREAD

**Issue by neiobaf** [NextINpact/nxiv6#148]
Bonjour, comme une image vaut un long discours, mon encart CES ressemble à ça :
![image](https://user-images.githubusercontent.com/5318316/34715184-02f255f0-f52c-11e7-9497-68224af497b6.png)

Le problème d'affichage se produit sous Chrome et Firefox.

**Comment by papci** [comment]
Bonjour, 

Un correctif avait déjà été planifié, il est désormais en ligne.
