### ISSUE TITLE
les deux ascenseurs

### ISSUE THREAD

**Issue by begit** [NextINpact/nxiv6#15]
Il m'est pénible de devoir remonter l’ascenseur de l'article pour voir correctement celui de droite de la liste des articles (il n'est que partiellement visible et on ne peut parfois plus le dérouler). De plus il ne garde pas sa position lors de la lecture d'un nouvel article, il faut donc retrouver où on était à chaque fois.

**Comment by Fu2chN** [comment]
Si tu scroll avec la mollette dessus ça ne marche pas chez toi ?
C'est vrai qu'il n’est pas très visible (pas assez sombre par rapport au fond de la colonne).

**Comment by begit** [comment]
pour le scroll ça marche mais pas de façon satisfaisante.
Comme sur l'image ci dessous, une fois arrivé en fin d'article, la colonne de droite est tronquée. On ne voit pas les premiers articles même en la remontant à son maximum. Il faut pour les voir remonter la colonne de gauche de l'article à son début pour voir les premiers articles de la colonne de droite. De plus comme le montre l'image la colonne n'apparait pas sur la totalité de la hauteur disponible en n'utilisant pas le bas de l'écran; ceci est particulièrement problématique sur les petits écrans.
[https://framapic.org/g8pIKNuUV4bD/0QSNyzu2abVs.jpeg](url)
De plus on perd le fil des articles de la colonne de droite dès que l'on clic sur un article pour le lire. Il faut à chaque fois rechercher où on en était dans le fil des articles de la colonne de droite.

**Comment by papci** [comment]
Bonjour,

Pourrais tu me préciser ta configuration complète ? Merci.

**Comment by begit** [comment]
Firefox
1920*1080
win10 64bits
i5-4210H 2.90Ghz
12 Go RAM

**Comment by papci** [comment]
A priori, il s'agit d'un problème lié a Adblock sur firefox. Par conséquent, nous ne pouvons apporter de correctif.

**Comment by begit** [comment]
Merci pour votre réponse, effectivement un de vos problèmes d'affichage vient de l'utilisation de AdBlock par vos lecteurs. Il pourrait tout de même être pris en compte et être corrigé afin d'améliorer la qualité de votre site pour les nombreux utilisateurs d'Adblock qui peuvent être tenté de souscrire en cas de satisfaction à un abonnement.
Le deuxième problème souligné lui ne vient pas d'Adblock. Votre site oblige à rechercher à chaque fin d'article, l'endroit où on était dans la colonne de droite et devoir descendre pour le retrouver.
Bonnes améliorations.
