### ISSUE TITLE
[LeBrief] Le bouton "Signalez une erreur" n'est pas affiché si l'option "Désactiver les boutons sociaux" est cochée

### ISSUE THREAD

**Issue by oliverpool** [NextINpact/nxiv6#151]
Le bouton "Signalez une erreur" n'est pas affiché dans une news du Brief si l'option "Désactiver les boutons sociaux" est cochée.

Actuellement lorsque cette option est cochée, seule le bouton de partage par mail est affiché.
Personnellement je préférerai voir juste :
- lien permanent
- signaler une erreur

(le lien permanent est pour moi plus pertinent que le bouton "envoyer par mail")

**Comment by darkweizer** [comment]
Le signaler une erreur est présent quand on désactive les boutons sociaux maintenant =).

Pour le lien permanent, je ne peux que plussoyer ! Ça ne fait pas partie des réseaux sociaux et devrait donc apparaitre si ceux-ci sont cachés. Pour partager c'est bien plus pratique que par email (on peut toujours faire clic droit -> copier le lien mais c'est 2 clics au lieu d'1 😬). Laisser les 3 (erreur, lien et email) me paraitrait logique 😃

**Comment by oliverpool** [comment]
@papci j'apprécierai aussi que le bouton "lien permanent" soit affiché lorsque les "boutons sociaux" sont désactivés. Ca vaut le coup d'ouvrir une nouvelle issue ou ce n'est pas la peine ?

Dans tout les cas, merci pour la résolution de ce petit bug :smiley:
