### ISSUE TITLE
Redirection vers commentaire d'un article #LeBrief depuis une page profil ne fonctionne pas

### ISSUE THREAD

**Issue by tl-pierre** [NextINpact/nxiv6#153]
Lorsqu’on clique sur le pseudo d’un NextInpactien, on est dirigé vers son profil et son historique de commentaires. A partir de là, lorsqu’on clique sur le titre d’un article sur lequel l’utilisateur a laissé un commentaire on est redirigé vers le commentaire en question sur la page de l’article. C’est bien pratique, mais cette fonctionnalité ne fonctionne pas pour les commentaires laissés sur des articles #LeBrief (lorsqu’on clique sur le titre, rien ne se passe). 

Merci d'avance !  😄

**Comment by darkweizer** [comment]
Petit supplément d'info :
Quand on clique, il ne se passe rien. Sauf si on ouvre dans un nouvelle onglet. Mais cela ramène vers la page de profil de l'utilisateur (car les url sont ceux du profils https://www.nextinpact.com/inpactien/xxxxxx (et non ceux de l'article) avec #/comment/xxxxxxx derrière. C'est là première partie qu'il faut changer en fait car la seconde est juste (si on la colle à la fin de l'url de l'article commenté, cela fonctionne ) 😃)

**Comment by pehadavid** [comment]
Un correctif a été déployé ces jours derniers, n'hésitez pas a commenter ici si vous constatez une regression.
