### ISSUE TITLE
Mot de passe avec caractères spéciaux : erreur

### ISSUE THREAD

**Issue by Gildas-GH** [NextINpact/nxiv6#160]
J'ai essayé de créer un compte NextInpact tout à l'heure. J'ai eu une erreur lors de l'inscription du compte.
C'est peut-être dû à mon mot de passe généré par KeePassXC. Il contient les cararctère spéciaux suivants : `^`, `<`, `.`, `{`, `<` et `$`, `'`.
J'ai ensuite changé mon mot de passe pour un constitué uniquement de lettres minuscules et majuscules et de chiffres, et le compte a pu être créé.
J'utilise Firefox 59 sur Fedora (Linux), et j'utilise (notamment) les addons uBlock Origin, uMatrix, KeePassXC-Browser.

![2018-04-06 17-44-05](https://user-images.githubusercontent.com/25692645/38432054-87539500-39c6-11e8-9045-088319e27835.png)
Sur ce screen l'URL de la page est https://compte.nextinpact.com/inscription.

Merci, Gildas.

**Comment by pehadavid** [comment]
Un fix sur les mots de passe a été déployé en début de semaine.
