### ISSUE TITLE
2nd article vignette avec titre long (3 lignes)

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#163]
Bug que j'avais remonté en septembre dernier (sans ouvrir de ticket, seulement par email) mais toujours pas corrigé. J'ouvre donc un ticket ! ^^.

Sur la page d'accueil, quand le second article de "Le meilleur de l'actualité high-tech ", en affichage vignette, fait 3 lignes, le 4ème article par totalement en live !
[https://image.noelshack.com/fichiers/2018/20/2/1526386911-capture-d-ecran-1.png](https://image.noelshack.com/fichiers/2018/20/2/1526386911-capture-d-ecran-1.png)

Aucun souci si cette article est en 1er, 3ème ou 4ème 
[https://image.noelshack.com/fichiers/2018/20/2/1526386912-capture-d-ecran-2.png](https://image.noelshack.com/fichiers/2018/20/2/1526386912-capture-d-ecran-2.png)

Testé sur plusieurs résolution d'écran.
[http://supportdetails.net/CO66B2X3](http://supportdetails.net/CO66B2X3) (ne pas tenir compte de la version de FF ! Elle est bien à 60. C'est un ancien lien, mais la résolution ne change pas)
[http://supportdetails.net/J2U5SLQF](http://supportdetails.net/J2U5SLQF) (autre ordi avec autre résolution mais même problème)

Cordialement.

**Comment by pehadavid** [comment]
un fix est passé il y a quelques jours. Merci pour le rapport complet ;)

**Comment by darkweizer** [comment]
Le problème est toujours présent :
[https://image.noelshack.com/fichiers/2018/24/5/1529077230-capture.png](https://image.noelshack.com/fichiers/2018/24/5/1529077230-capture.png) 

P.S.: j'ai rechargé sans le cache pour être sûr.

**Comment by pehadavid** [comment]
j'ai parlé un peu vite, le fix est developpé, mais n'est pas encore passé en prod, je réouvre.

**Comment by darkweizer** [comment]
Ceci explique cela ^^ !

**Comment by darkweizer** [comment]
[https://image.noelshack.com/fichiers/2018/27/5/1530874480-capture.png](https://image.noelshack.com/fichiers/2018/27/5/1530874480-capture.png)
Le fix a été déployé et ça fonctionne impeccablement ! 😀.
Vous pouvez clôturer le ticket :).
