### ISSUE TITLE
Overlay légende image

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nxiv6#164]
Bonjour,

L'Overlay de la légende des images empiète sur les images et gène la lisibilité des informations présente en bas de celles-ci. Exemple [sur cette article](https://www.nextinpact.com/news/106626-telecoms-apres-bonne-annee-2017-arcep-ne-soppose-plus-a-consolidation.htm).
J'ai pris des captures sinon : 

- [capture 1](https://image.noelshack.com/fichiers/2018/21/4/1527166890-overlay.png)
- [capture 2](https://image.noelshack.com/fichiers/2018/21/4/1527166890-overlay-2.png)

Par contre [ici](https://www.nextinpact.com/news/105151-apple-suivez-conference-en-direct-des-19h.htm) ça ne gène pas car il n'y a pas de lecture en bas des images.

Cordialement.

**Comment by pehadavid** [comment]
Bonjour,
Effectivement, on a des solutions en tête mais on manque un peu de temps pour les mettre en oeuvre dans l'immédiat. Cependant, je ferme car la fonctionnalité est déjà dans notre backlog.
