### ISSUE TITLE
Connection impossible: erreur de cookie

### ISSUE THREAD

**Issue by hyviquel** [NextINpact/nxiv6#165]
Je n'arrive plus a me connecter a mon compte depuis quelques semaines (argg). Sous MacOs tout fonctionnait bien mais depuis que je suis repassé sous Ubuntu (17.10 et 18.04) avec Firefox (60), j'obtiens un magnifique "un problème est survenu, assurez vous que votre navigateur internet accepte les cookies". J'ai essayé de désactivé mes extensions (dont ublock origin) au cas où mais j'obtiens toujours le même message.
J'ai essayé d'envoyer ce message par le formulaire du site mais j'ai aussi une erreur lors de la validation...

Une idée de la source de mon problème ??

**Comment by hyviquel** [comment]
Même problème avec un chromium tout neuf sans extension mais par contre ca fonctionne bien sous iOS avec safari.

**Comment by hyviquel** [comment]
J'ai fait un post sur le forum pour voir si un inpactien aurait une solution pour moi: https://forum.nextinpact.com/topic/174081-connexion-au-site-impossible-cookie/

**Comment by pehadavid** [comment]
Il vaut mieux que tu contactes le support (support @ nextinpact .com), tu obtiendras une aide spécifique à ton compte.

**Comment by hyviquel** [comment]
Probleme resolu avec l'aide des inpactiens du forum (un peu deçu du support de Nxi pour le coup, je n'ai pas eu la moindre reponse): Apparement le site ne supporte pas les mots de passe complexes généré par keepass (VaSVZK4uv2<X]=d<tu) j'en ai mis un plus simple et ça fonctionne.
C'est un peu le comble pour un site qui conseille keepass hahahaha
