### ISSUE TITLE
Impossible d'envoyer un message via le formulaire de contact

### ISSUE THREAD

**Issue by PascalLeMerrer** [NextINpact/nxiv6#168]
J'ai une erreur systématique quand j'essaie de valider le contenu du formulaire.

'Une erreur s'est produite. Vérifiez les données du formulaire.'

Mon adresse email est correcte, j'ai choisi une catégorie dans la liste déroulante ('proposer un communiqué de presse'). 

Mon message initial était assez long, et comportait des URL ; je l'ai réduis sans que cela résolve les problèmes. Voici son contenu actuel, qui ne passe toujours pas :

```
Bonjour

Fency Drone est un serious game que j'ai créé avec 3 collèguesparce que je voulais éviter que mes enfants, tombent dans les nombreux pièges tendus sur la toile.

Il est gratuit, sans pub, et ne collecte bien entendu aucune donnée personnelle !

Fency Drone est dispo sur Android et sur iOS
Vous serait-il possible de publier un article sur ce jeu SVP ?

Cordialement
```

**Comment by pehadavid** [comment]
Bonjour,

Pourrais tu me donner la configuration complète de ton environnement ?

Merci

**Comment by ncandelier** [comment]
Bonjour
Même problème ici. 'Une erreur s'est produite etc...'
Windows 10. FF 60.0.2
Même problème sous Chrome.
Cordialement

**Comment by khena** [comment]
Bonjour, même problème par ici, y compris en mode invité (sans plugin)
Chrome 67.0.3396.99
Windows 10

**Comment by khena** [comment]
Erreur identique avec Edge.

**Comment by imcoyote** [comment]
Erreur identique sur Edge, Firefox, chrome ou opera

**Comment by jxerome** [comment]
Semble pareil pour moi. Mais je n'ai aucun message visible. (Avec Firefox)

**Comment by Dbroqua** [comment]
Idem avec Debian/FF 61.0 (64b).

Route appellée en POST : https://www.nextinpact.com/Home/CreateRequest

Status : 200

Contenu de la réponse : 
`{"sucess":false}`

Contenu du POST (formdata): 

```
replyTo | contact@***
requestContent | Bonjour,  Je+voulais+m'inscrire+pour+vous+soutenir+et+en+regardant+les+tailles+pour+les+tee+shirt+du+pack+2017+(j'ai+déjà+celui+de+2014)+je+n'ai+pas+vu+de+taille+M+:'(+.  Allez+vous+le+remettre+dans+vos+options+?  Merci, Damien
requestType | 2
```


Par ailleurs au niveau de chargement de la page il y a une erreur sur la tentative de chargement du reCaptcha google

**Comment by IPv777** [comment]
Hello,

même problème ici :/
https://i.imgur.com/btdfNK5.png

Firefox 61 avec ces extensions : 
https://i.imgur.com/Jp0rrhO.png

Bonne journée à tous
