### ISSUE TITLE
Impossible d'utiliser un code d'abonnement pour les comptes la presse libre

### ISSUE THREAD

**Issue by jxerome** [NextINpact/nxiv6#169]
Lors que vous avez un compte réglé sur la presse libre, il n'est pas possible de bénéficier des code d'abonnements d'un mois fournis après la quête Ulule.

**Comment by pehadavid** [comment]
Bonjour,

C'est volontaire : tout les abonnements réglés mensuellement ne peuvent pas bénéficier d'un changement d'offre sans résilier préalablement.
