### ISSUE TITLE
La redirection à partir de www.pcinpact.com ne fonctionne plus (erreur 404)

### ISSUE THREAD

**Issue by donpedrus** [NextINpact/nxiv6#171]
J'utilise l'adresse www.pcinpact.com pour accéder au site et je ne veux pas changer car je n'ai jamais pu intégrer le changement de nom du site.
Depuis peu, la redirection est indisponible et l'url affiche une erreur 404.
Pour information, ce problème a des conséquences graves, en effet je pars vomir à chaque fois que j'écris nextinpa

**Comment by pehadavid** [comment]
la redirection est active, il faut peut-être attendre un petit peu que les DNS  soient correctement propagés.

**Comment by donpedrus** [comment]
Excellent ! Mon transit intestinal va pouvoir reprendre son cours normal.
