### ISSUE TITLE
Problème Abonnement premium

### ISSUE THREAD

**Issue by Atchoums** [NextINpact/nxiv6#178]
Bonjour 
Je vous contact pour vous signalez le problème technique que j'ai eu lors de mon inscription pour l'abonnement premium découverte de 30 euros par an.
J'ai reçu un mail avec l'offre avec une redirection vers ce site : "https://compte.nextinpact.com/inscription-abonnement?type=1", je coche les 1 an, je descend et dans la section "finalisez votre commande" en créant un compte pas moyen de pouvoir continuer, le bouton ne fonctionne pas. J'ai du allé sur le site de next inpact créer un compte et revenir sur cette page pour pouvoir choisir "j'ai déjà un compte" et là, le bouton me parait de continuer.
De plus j'avais essayé avec un autre navigateur (chrome) et quand j'ai cliqué sur continué je suis tombé sur une page " Server Error in '/' Application.
Pour le navigateur je suis sous Firefox.
Voila mon retour de nouveau abonnée ^^
En espérant que cela puisse vous aidez
Cordialement

**Comment by pehadavid** [comment]
Bonjour,

Pour tout souci avec l'abonnement Premium, il faut passer par le formulaire de contact (https://www.nextinpact.com/a-propos.htm#nouscontacter_section)

Merci ;)
