### ISSUE TITLE
Absence de Content-Type: pour les images via cdn/cdn2

### ISSUE THREAD

**Issue by Oumph** [NextINpact/nxiv6#179]
Bonjour,

LinuxFr.org serait ravi d'aider à diffuser le schéma résumant l'article 13 https://cdn.nextinpact.com/images/bd/news/medium-173326.png (sous licence CC By SA 3.0). Mais on a un souci technique actuellement : le fichier est renvoyé sans Content-Type (avec ou sans HTTP/2) et notre cache d'image n'aime pas trop ça. 

2019/03/14 09:40:55 https://cdn2.nextinpact.com/images/bd/news/medium-173326.png has an invalid content-type: 
2019/03/14 09:46:52 https://cdn.nextinpact.com/images/bd/news/medium-173326.png has an invalid content-type: 

Merci pour votre taf en tout cas.

**Comment by pehadavid** [comment]
Bonjour,

Effectivement : nous allons étudier ça de plus prés. En attendant, vous êtes libre de télécharger l'image et de l’héberger sur un autre service.

**Comment by pehadavid** [comment]
Le content-type est désormais présent dans la réponse.
