### ISSUE TITLE
Site web mobile : désactivation des boutons sociaux non prise en compte

### ISSUE THREAD

**Issue by Leepic** [NextINpact/nxiv6#185]
L'affichage d'un article sur le site web mobile https://m.nextinpact.com ne prends pas en compte la désactivation des boutons sociaux dans les paramètres du compte.

### Reproduction

1. Cocher « Désactiver les boutons sociaux » dans le compte
2. Ouvrir un article quelconque, exemple avec [Extensions Firefox inopérantes : un premier correctif en déploiement](https://m.nextinpact.com/news/107844-toutes-extensions-firefox-devenues-inoperantes-fait-dun-certificat-expire.htm)
3. Les boutons sociaux sont affichés
![firefox-article-site-mobile-boutons-sociaux-affiches](https://user-images.githubusercontent.com/10730819/57194682-d21e2f00-6f49-11e9-8f57-c77219a76937.png)

Note : aucun problème sur le site web https://www.nextinpact.com

### Actions effectuées
* cocher/décocher l'option
* Me déconnecter/reconnecter
* Changer de navigateur et d'OS

#### Mobile

- Firefox Nightly 68.0a1 (2019-05-04)
- Samsung Internet (9.2.00.70)
- Android 8.1.0

#### PC

- Firefox 66.0.3 64 bits
- Linux Mint 18.3 64 bits

**Comment by pehadavid** [comment]
Les options de la version mobile et de la version classique sont distinctes. Ça ne sera plus le cas avec la v7, mais pas pour le moment ;)
