### ISSUE TITLE
Site web mobile : manque icône de notification de réponse aux commentaires

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/nxiv6#186]
Sur mobile (Firefox, 1080x1920 en mode portrait), il manque le bouton des notifications (orange, avec le nombre de réponses aux commentaires postés).

**Comment by pehadavid** [comment]
Hello,

La version mobile ne dispose pas de système de notification : Ça ne sera plus le cas avec la v7, mais pas pour le moment ;)
