### ISSUE TITLE
Header invalide sur les flux RSS

### ISSUE THREAD

**Issue by yoshiyes** [NextINpact/nxiv6#192]
Bonjour,

Il semble que le header du flux RSS de nextinpact soit invalide.

Depuis une application en NodeJS, une erreur apparaît à chaque tentative de récupération d'un flux rss.
![image](https://user-images.githubusercontent.com/20050570/65885230-8bb6ea00-e39a-11e9-924d-8394cac2ce2c.png)
Le problème semble venir de la réponse du serveur et plus particulièrement du header qui semble être malformé.

Voici un exemple de code qui crée l’erreur : 
```
fucntion getNextinpactRss() {
return fetch('https://www.nextinpact.com/rss/nobrief-noih.xml')
  .then((response) => response.text())
}
```

NodeJs 12
Flux RSS concerné -> https://www.nextinpact.com/rss/nobrief-noih.xml

**Comment by pehadavid** [comment]
Sécurité Botscorner
