### ISSUE TITLE
Forum NextInpact : impossible d'utiliser le formulaire nous contacter, erreur de récupération de captcha

### ISSUE THREAD

**Issue by fraynaud33** [NextINpact/nxiv6#193]
Bonjour,
n'arrivant pas à me connecter sur le forum j'ai voulu vous écrire, et je n'ai pas réussi : erreur sur le captcha "Impossible d'établir une connexion avec le service reCAPTCHA. Veuillez vérifier votre connexion Internet, puis actualiser la page pour afficher une image reCAPTCHA."
![image](https://user-images.githubusercontent.com/26875828/67029618-f2176880-f10d-11e9-9d56-656ab66ee145.png)
Reproduit sur Firefox 69.0.2 et Chrome 79 sur windows 10 et Chrome 77 sur S8 Android 9

**Comment by pehadavid** [comment]
Bonjour,

Le forum est géré par la communauté. Je fais cependant remonter votre problème aux admins de ce dernier ;)
