### ISSUE TITLE
Flux RSS bloqués depuis certains hosts ?

### ISSUE THREAD

**Issue by boccheciampe** [NextINpact/nxiv6#196]
Hello,

Depuis mon réseau (situé en France, une seule IP publique), impossible de consulter les flux nextinpact, notamment les news et bons plans, et ce quel que soit le client (thunderbird, client sur mobile ou un simple curl). Dans tous les cas la réponse ne contient pas le contenu du xml demandé.

Exemple avec la commande 'curl https://www.nextinpact.com/rss/bonsplans.xml' :

< html>
< head>
< META NAME="robots" CONTENT="noindex,nofollow">
< script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
< /script>
< body>`

Avec la même machine, mais avec une connexion différente de celle de mon FAI (via un VPN par exemple, en France ou ailleurs), je reçois bien les flux.

Une idée ... ?

Merci d'avance :)

**Comment by pehadavid** [comment]
changement de CDN, le souci ne devrait plus apparaitre
