### ISSUE TITLE
Impossible d'imprimer/exporter la facture

### ISSUE THREAD

**Issue by hoh** [NextINpact/nxiv6#199]
**Il m'est impossible d'imprimer ou d'exporter en PDF la facture émise par [compte.nextinpact.com](https://compte.nextinpact.com/gestion-util).**

La facture accessible via la [page de profil](https://compte.nextinpact.com/gestion-util), est fournie sous forme d'une page web et non d'un document PDF. _Imprimer_ cette page au format PDF avec Firefox me fournit un document PDF contenant une page A4 vide.

Détails techniques:
- URL de la facture web: https://compte.nextinpact.com/Account/GetPremiumFacture?order=XXXXX-XXXXXXXXX-XXXXXX 
- Navigateur: Firefox 73.0, Ubuntu amd64.

**Comment by pehadavid** [comment]
bonjour,
Pour tout probleme d'abonnement ou de facturation, il faut contacter le support : https://www.nextinpact.com/a-propos.htm#nouscontacter_section
