### ISSUE TITLE
Problème de chargement des commentaires en mode incognito

### ISSUE THREAD

**Issue by dydil** [NextINpact/nxiv6#20]
Bonjour,

Régulièrement, il a un bug avec le chargement des commentaires en mode incognito.
"Chargement des commentaires" est affiché, mais la page ne charge que du blanc. Ce blanc s'ajoute à l'infini toutes les quelques dixièmes de seconde jusqu'à ce que je ferme la page. Comme vous pouvez voir sur le screenshot, la page est entièrement remplie de blanc.

![capture](https://cloud.githubusercontent.com/assets/18531651/14706700/9e0151e6-07c0-11e6-936e-c49b23a89a98.PNG)

Pour reproduire, je ne suis pas certain car ça ne le fait pas à chaque coup, mais à chaque fois j'ai fait ça : 
- Lire un article sans descendre assez pour charger les commentaires (mieux encore, s'il n'y a encore aucun commentaire je crois que ça le fera à chaque fois)
- Fermer l'onglet
- Attendre que des commentaires soient postés
- Plus tard, depuis la liste des articles, cliquer directement sur "(X commentaires - Lire)"
- Les commentaires ne chargent pas et la page se remplit de blanc en continu jusqu'à fermeture de l'onglet

Reproduisible sur n'importe quelle version récente de firefox (ça fait des mois que ça existe, voire même depuis le début mais j'en suis pas certain).

**Comment by papci** [comment]
Bonjour,

Nous venons de réussir à reproduire ;) on va examiner  ça de plus près.

**Comment by stoane** [comment]
Le bug est toujours présent, des nouvelles quand à sa résolution ?

**Comment by papci** [comment]
Un fix a été appliqué ce jour. je laisse ouvert quelques temps si jamais vous constatez à nouveau le souci.

**Comment by stoane** [comment]
C'est réglé de mon coté. Merci PA !
