### ISSUE TITLE
Les images du site ne chargent plus

### ISSUE THREAD

**Issue by yannlairdc** [NextINpact/nxiv6#201]
Bonjour,

Cela fait a peu pres une semaine que plus aucune image ne charge sur le site pour moi:

![image](https://user-images.githubusercontent.com/50559695/77369683-486e8e80-6db3-11ea-8aed-beaa0527f545.png)

Il me donne une erreur 502 Bad getaway pour toutes les images, il apparait donc qu'il y ai un probleme avec votre CDN.

Voici le header de l'erreur:
----
removed 
---

Je ne peux plus voir les posts de Flock alors que je suis abonnes de premieres heures :(

Petite precision, j'habite a Sydney (operateur TPG), peut etre que cela expliquer le probleme de configuration du CDN.

Cheers,
Baradhur.

**Comment by pehadavid** [comment]
j'ai édité le ticket car il contenait le cookie d'identification. Le message étant au support, tout sera traité la bas ;)
