### ISSUE TITLE
News - nouveaux commentaires 

### ISSUE THREAD

**Issue by stantrinity** [NextINpact/nxiv6#21]
Sur une news, on nous indique le nombre de nouveaux commentaires par rapport à notre dernière lectures des commentaires, ex : 53+50, en cliquant sur le lien je m'attendais à qu'il me dirige au 54 ème  commentaire cependant il me dirige vers la dernière page des commentaires.

**Comment by papci** [comment]
Bonjour,

Sur quelle version de NXi ? (mobile ou desktop ?)

**Comment by stantrinity** [comment]
desktop

**Comment by papci** [comment]
Peux-tu me faire un rapport complet (configuration utilisée, nombre de commentaires par page etc.)

**Comment by stantrinity** [comment]
je te remonte et je serais plus précis cela quand j'aurais un peu plus de temps, d'ici la fin du week end.
