### ISSUE TITLE
impossible d'accéder aux forums en mode connecté

### ISSUE THREAD

**Issue by acvvd** [NextINpact/nxiv6#23]
quand je m'authentifie sur NXI et que je veux aller sur les forums, il me met une page blanche ou une erreur 500. En anonyme, cela fonctionne.
J'ai testé sous windows avec FFx, sous Linux avec FFx et Chromium.

**Comment by smariel** [comment]
Idem sur mac avec les mêmes navigateurs.

**Comment by bastien-c** [comment]
Bonjour, 

On a quelques problèmes avec le forum en ce moment, on fait le maximum pour le rétablir au plus vite.

**Comment by papci** [comment]
Bonjour,

ça devrait être réglé désormais ;)
