### ISSUE TITLE
Erreur sur le formulaire "Nous contacter"

### ISSUE THREAD

**Issue by Berbe** [NextINpact/nxiv6#28]
- "Poser une question à la rédaction" sélectionné
- Adresse courriel remplie
- Message rempli

Message d'erreur "Une erreur s'est produite. Vérifiez les données du formulaire."

Il n'y a pas de surlignement d'un champ ni d'indication supplémentaire sur le "problème" rencontré.

- Windows 7 x64
- Firefox 47.0 x64

**Comment by olivier-collet** [comment]
J'ai aussi cette erreur.

**Comment by Nightmaster** [comment]
Pour avoir le même soucis, je pense que c'est dû au fait que le captcha (qui est obligatoire pour valider le formulaire) ne s'affiche. C'est notamment mon cas sur mobile: firefox iOS l'affiche mais impossible de le faire, safari iOS: pas d'affichage.

**Comment by Nightmaster** [comment]
Rectification: pour safari, il s'agit du blocker Focus de Firefox qui posait problème, une fois désactivé, ça fonctionne !

**Comment by olivier-collet** [comment]
Effectivement, là je vois un capcha et le problème semble résolu.

**Comment by papci** [comment]
Je ferme, étant donné que c'est résolu. Merci pour vos multiples tests :+1:
