### ISSUE TITLE
Image d'article qui ne s'affiche pas sur Safari 9.1.1

### ISSUE THREAD

**Issue by CNek** [NextINpact/nxiv6#29]
Bonjour,
.container_main_image_article n'affiche pas l'image de l'article si il a été chargé à partir d'un lien sur le site, ça fonctionne si on recharge la page.

[Capture](http://i.imgur.com/aSHwgIt.png)

Safari 9.1.1 et OS X 10.10.5

**Comment by papci** [comment]
Bonjour,

Nous ne reproduisons pas. As-tu des extensions installées ?

**Comment by CNek** [comment]
ABP et Ghostery mais NXI est sur liste blanche.
Le bug ne se reproduit pas systématiquement.
Rien dans la console.

**Comment by papci** [comment]
Problème lié à safari et non au site.
