### ISSUE TITLE
Impossible de se logguer sur la version Android

### ISSUE THREAD

**Issue by Olivier34** [NextINpact/nxiv6#3]
J'ai testé de nombreuses fois mon identifiant/pass sur navigateur, et la même chose dans l'app Android ne fonctionne pas.

Vus les commentaires sur le PlayStore, je ne suis pas le seul...

**Comment by papci** [comment]
Hello,

Nous ne développons pas les applications mobiles. Cependant, le problème est déjà connu et une mise à jour est prévue, mais je ne peux pas donner de date. Merci  ;)

**Comment by Olivier34** [comment]
Pourtant elle est bien éditée par  INpact mediagroup...

**Comment by papci** [comment]
Nous sommes éditeurs des appli, mais pas dev :)

**Comment by Olivier34** [comment]
Vous me décevez, la consultation mobile est plutôt importante de nos jours :)

**Comment by papci** [comment]
On aimerait tout internaliser mais nos moyens ne nous le permette pas toujours.
