### ISSUE TITLE
(Im)possible de se connecter (problème de cookie) + raison précise

### ISSUE THREAD

**Issue by Ski-lleR** [NextINpact/nxiv6#30]
OS> Debian Sid
Navigateur> Firefox 48.0a2 vierge ("~/.mozilla" / ".cache/.mozilla" supprimés pour voir si ça venait des plugins / réglages)

1. Donc sur un Firefox vierge, j'active l'option "Mode de navigation privée", et je décoche l'option global "Accepter les cookies".

2. Une fois sur http://www.nextinpact.com, je donne la permission explicite au site de pouvoir créer des cookies (avec le cadenas) et je recharge la page.

3. Je tente de me connecter, et ça me dit "Un problème est survenu, assurez-vous que votre navigateur accepte les cookies".

4. Je re-coche "Accepter les cookies" au niveau global, la connexion fonctionne.

Puis en fait j'ai vite compris pourquoi, en fait quand on est pas abonné on accède au site en HTTP, du coup si on donne la permission de créer des cookies avec l'interface de permissions (clique sur le cadenas -> Plus d'informations) sa créer une règle "http://www.nextinpact.com", sauf que le formulaire de connexion appel "https://www.nextinpact.com......".

Pour pouvoir se connecter il faut donc créer une règle manuellement dans Préférences -> Vie privée -> Exceptions... en mettant "https://www.nextinpact.com".

Du coup je suis en train de me dire qu'il n'y a rien que vous puissiez réellement faire, car l'option HTTPS est réservée au premium, et vous ne pouvez pas appeler /Login en HTTP pour que ça concorde avec la règle de cookie qui se créer avec l'interface "de base".

Au final ça fait juste ressortir le problème de mixed content.

**Comment by papci** [comment]
Bonjour,

Merci pour le rapport ultra complet.

Effectivement, c'est un problème que l'on ne peut pas régler de notre côté. Nous travaillons à rendre le site full HTTPS pour l'ensemble de nos lecteurs, et le souci ne se présentera plus de facto.
