### ISSUE TITLE
Soldes d'hiver en été

### ISSUE THREAD

**Issue by Mystell** [NextINpact/nxiv6#32]
Un petit "bug" très facile a résoudre:

Le title du lien "voir toute les offres" en bas de pas pour les soldes d'été est:

title="Tous nos bons plans pour les soldes d'hiver 2016"

**Comment by papci** [comment]
Bonjour, merci pour la remontée, mais le bloc va disparaître sous peu. On fera plus attention la prochaine fois ;)
