### ISSUE TITLE
Boutons sociaux affichés même en les désactivant

### ISSUE THREAD

**Issue by Anthony25** [NextINpact/nxiv6#34]
Bonjour,
J'ai activé l'option permettant de désactiver les boutons sociaux mais depuis quelques temps les boutons share via facebook et twitter sont affichés dans la top bar des articles. Pour autant, lorsque je clic dessus, je ne vois aucune requête effectuée ("cliquer sur les 2 boutons ne fait rien").

![nextinpact_bugreport](https://cloud.githubusercontent.com/assets/1174685/16738369/aae14532-4795-11e6-952b-35cfdc8d7e35.png)

Ce n'est pas un bug très génant puisqu'en regardant rapidement, je n'ai pas l'impression que du code de facebook ou twitter soit intégré, mais l'on pourrait croire que l'option ne fonctionne pas bien.

Merci !

Edit: testé sous firefox 47 et chromium

**Comment by papci** [comment]
c'est corrigé et en ligne ;)

**Comment by Anthony25** [comment]
Cool, merci !
