### ISSUE TITLE
renouvellement abonnement et paiment bitcoin

### ISSUE THREAD

**Issue by ticapix** [NextINpact/nxiv6#36]
Bonjour,

J'ai essaye de renouveler mon abonnement avec paiment en bitcoin mais j'obtiens une erreur sur le site de payzen avec uniquement le message 'An error occurred during the payment request, the merchant website has been informed of the impossibility to complete the transaction.'
L'url étant https://secure.payzen.eu/vads-payment/.
![error payzen](https://cloud.githubusercontent.com/assets/3089662/16999037/4d1507e4-4ebc-11e6-96be-8c4498566a27.jpg)

**Comment by papci** [comment]
Bonjour,

Pour ce genre de cas, il vaut mieux passer par notre formulaire de  support ([ici](http://www.nextinpact.com/a-propos.htm#nouscontacter_section)).

Merci ;)
