### ISSUE TITLE
Amélioration de la lettrine du chapeau des articles 

### ISSUE THREAD

**Issue by bgatellier** [NextINpact/nxiv6#38]
Bonjour,

En vu d'améliorer l'affichage de la lettrine des chapeaux des articles du site, je vous propose [les améliorations suivantes (CodePen)](http://codepen.io/bgatellier/pen/OVZOzL). En résumé, suppression des marges sur le `::first-letter`, et ajout d'un `line-height` de valeur égale à une double hauteur de ligne du chapeau.
Testé sur IE 11 / Edge, Firefox et Chrome. A vous de voir ensuite si ces modifications fonctionnent avec les navigateurs que le site supporte.

**Comment by papci** [comment]
Bonjour,

L'amélioration a été basculée en production.
