### ISSUE TITLE
touche de navigation dans la version classique du site

### ISSUE THREAD

**Issue by ggahdeh** [NextINpact/nxiv6#4]
Les touches de navigation dans la version classique du site, J pour précédent et K pour suivant par exemple pour naviguer d'une news à l'autre ne fonctionnent plus depuis une bonne semaine.
Mon environnement:
http://supportdetails.net/18HLUA4A

**Comment by papci** [comment]
Résolu ;)

**Comment by ggahdeh** [comment]
Merci
