### ISSUE TITLE
Utilisation des espaces insécables

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nxiv6#40]
En Français, '«' est suivit d'un espace insécable, ainsi que '?' et '»' en sont précédé d'un (je recommande la lecture de https://fr.wikipedia.org/wiki/Espace_insécable pour voir tous les caractères qui doivent être précédé ou suivit d'un espace insécable)

Actuellement, sur NI, on peut voir des horreurs (désolé pour le terme horreur) comme le titre de http://www.nextinpact.com/news/100890-departs-volontaires-chez-sfr-ce-que-contient-accord-new-deal-ce-quen-disent-syndicats.htm ou dans l'article http://www.nextinpact.com/news/98844-drown-quand-failles-sslv2-permettent-decrypter-connexions-tls.htm avec a chaque fois des retours à la ligne inconvenant. Bien sûr, ce problème est présent dans d’innombrables autres articles.
(exemple avec le point d'interrogation dans cet article http://www.nextinpact.com/news/98893-les-deputes-rejettent-l-activation-obligatoire-cameras-pietons-lors-controles-d-identite.htm)

Corriger cela n'est pas excessivement dur, mais améliorerait grandement la lecture.

**Comment by Nil-av** [comment]
Je rebondis sur ce sujet pour saluer le fait que vous en mettiez désormais dans les nombres. La séparation des milliers étaient souvent chaotiques.

**Comment by Cqoicebordel** [comment]
Yeah !!!!

**Comment by Cqoicebordel** [comment]
@papci, il semblerait qu'une régression se soit glissée dans le code : tous les liens de mon premier post ont à nouveau le soucis, et même des articles récents, comme la dernière phrase de  https://www.nextinpact.com/news/104116-dans-espace-chine-continue-ses-essais-avant-construction-dune-station-permanente.htm

Du coup, je pense qu'il faudrait rouvrir ce bug...

**Comment by papci** [comment]
je lis, mais la mise en page et le contenu (ainsi que le formatage) est laissé libre à la rédaction pour de multiple raisons. Il vaut mieux contacter la rédaction afin de leur faire part de la suggestion :)

**Comment by Cqoicebordel** [comment]
Ca marche, pas de soucis. Je m'en occupe.

**Comment by Cqoicebordel** [comment]
La réponse de la rédaction est que le site ne permet pas de faire ces corrections automatiquement, et qu'ils doivent le faire à la main.

Du coup, je demande directement, est-il possible d'automatiser ces corrections ?
