### ISSUE TITLE
Layout de "Le meilleur de l'actualité" cassé si on change de filtre

### ISSUE THREAD

**Issue by Altair31** [NextINpact/nxiv6#41]
Bon, la démarche est assez facile à reproduire :
Depuis la page d'accueil, changer le filtrage de la section "La high-tech en continu" et les images de "Le meilleur de l'actualité" resterons en miniature.

Navigateur: Google Chrome 52.0.2743.116 m [Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36]
Extensions: uBlock Origin, Ghostery (désactivées pour NXI), Privacy Manager (activée)
Status: Abonné, pub et trackers désactivés, HTTPS activé

**Comment by papci** [comment]
Je ferme, le bug a été fixé par @ryuKKu- et mis en prod fin aout ;)
