### ISSUE TITLE
Disparition de la mention "Réponse à" après une édition du commentaire

### ISSUE THREAD

**Issue by Nil-av** [NextINpact/nxiv6#43]
Difficile de m'exprimer rien qu'avec le titre.

Sous Chrome (pas essayé les autres navigateurs), lorsque l'on répond à quelqu'un (bouton répondre). Une fois le commentaire posté, si je l'édite, la petite mention au-dessus du commentaire qui dis que je réponds à XXX n'est plus visible. Cela donne l'impression que le système de commentaire a eu un couac et que la personne à qui je réponds n'aura pas de notification notamment et que les autres lecteurs ne sauront pas que je fais référence à tel ou tel commentaire.

Toutefois, si j'actualise la page de l'article ou si je passe d'une page à une autre dans les commentaires, la mention apparaît bien. Ce n'est donc pas un problème très grave, juste un peu perturbant.

**Comment by papci** [comment]
Merci pour la remontée. Il existe effectivement plusieurs problèmes avec l'éditeur de commentaires en mode wysiwyg. Nous avons prévu de refondre cette partie du site dans une version ulterieure, c'est pourquoi nous ne pouvons pas corriger dans l'immédiat.
