### ISSUE TITLE
Abonnement impossible à cause d'Adblock

### ISSUE THREAD

**Issue by pierrerigal** [NextINpact/nxiv6#45]
Hello,

Membre de longue date j'ai décidé de m'abonner depuis quelques temps. Sur la page d'abonnement en bas, le formulaire de connexion ne se charge pas, impossible de saisir user et mot de passe, aucun champs disponible. J'ai laissé tombé, pressé.

Une semaine plus tard, je retente, même problème. Je décide de revenir sur le site, de me connecter d'abord pour m'abonner ensuite. Je n'ai plus mon mot de passe en tête, je demande à le réinitialiser, idem, aucun formulaire sur la page de réinitialisation. Pressé également, je laisse tombé, je cherche un lien vers un bug tracker sur NXI, pas trouvé. 

Rebelotte ce matin. Sur un article intéressant je craque :) je réessaye de m'abonner.

Même problème mais j'ai 10min devant moi :) 

Me revoilà sur compte.nextinpact.com, et pas de formulaire. Clic droit, inspecter, le code est bien là, juste masqué. Je vire le display none et revoilà le formulaire. Bizarre. Pareil sur Chrome et Firefox ! En haut à droite un icone rouge adbloc allumé... what ? Normalement j'ai désactivé adblock sur NXI depuis une éternité. 

Retour sur le site, adblock en vert. Retour sur le mot de passe oublié, adblock en rouge. Là j'ai tilté. On change de domaine. La gestion du compte (et l'abonnement !!!) se fait sur compte.nextimpact.com. En créant ma règle adblock j'ai pas exclu compte.nextimpact.com juste www. 

Du coup adblock est resté actif sur la partie compte, et il entraine un bug qui masque les formulaires pour se connecter, renouveler son mot de passe... mais aussi pour s'abonner.

Faut vite corriger ça ! On est pas tous des geek css. 

Bref, je voulais vraiment m'abonner !

**Comment by papci** [comment]
Bonjour,

Effectivement, adblock est responsable de ce comportement. Nous allons regarder ce que l'on peut faire.

**Comment by papci** [comment]
Nous appliquer un correctif, AdBlock ne devrait plus être un souci pour accéder aux différents champ du formulaire.

**Comment by pierrerigal** [comment]
> Nous appliquer un correctif 

Moi content ;)

Bonne journée à vous 👍
