### ISSUE TITLE
"Mot de passe oublié" non fonctionnel

### ISSUE THREAD

**Issue by philou66** [NextINpact/nxiv6#46]
Le formulaire "mot de passe oublié" ne fonctionne pas sous Firefox 48.0.2, toutes extensions désactivées.
Le champ "e-mail" s'affiche une fraction de seconde et disparait.

![nxi](https://cloud.githubusercontent.com/assets/22369010/18745924/a909c44c-80c4-11e6-9e2c-65999f1ebf24.png)

**Comment by papci** [comment]
Hello, 
Est-tu sur qu'AdBlock est bien désactivé ?
Merci.
