### ISSUE TITLE
Objet d'email

### ISSUE THREAD

**Issue by Jyhel** [NextINpact/nxiv6#47]
Bonjour,

En objet du mail portant sur les bouquets Canal, voici ce qui est affiché :
 =?utf-8?Q?=F0=9F=94=A5=C2=A0On=20fait=20le=20point=20sur=20les=20bouquets=20=C2=AB=20By=20Canal=20=C2=BB=20de=20Free=20et=20Orange=2C=20Essentiel=20fa

**Comment by papci** [comment]
Avec quel client mail rencontres-tu le souci ?

**Comment by Jyhel** [comment]
J'ai eu ça sur le webmail de yahoo.

**Comment by papci** [comment]
Il s'agit d'un problème lié au webmail (qui ne semble pas supporter l'utf 8 / les emoji).
