### ISSUE TITLE
Afficher la date d'un article au format humain

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nxiv6#48]
Si on compare les versions desktop et mobile de NI sur l'affichage de la date de rédaction d'un article, voici ce que l'on obtient :
https://m.nextinpact.com/news/101754-replay-biometrie-ogm-et-animation-a-ancienne.htm

> Rédigé par Guénaël Pépin 
> Le vendredi 14 octobre 2016 à 17:50

http://www.nextinpact.com/news/101754-replay-biometrie-ogm-et-animation-a-ancienne.htm

> Publiée le 14/10/2016 à 17:50

La version mobile de l'affichage de la date est beaucoup plus claire, lisible, et chaleureuse.

Je souhaiterais donc que l'affichage de la date sur la version desktop du site suive le même format long.
Si en plus, le nom de l'auteur était ajouté également, même avec le bloc auteur juste en dessous, ce serait encore mieux (mais j'y crois pas trop...)

**Comment by Cqoicebordel** [comment]
Suite à la mise à jour 6.1, je fais un up. Le changement demandé ne me semble pas trop radical, ni difficile à mettre en place :)

**Comment by papci** [comment]
Salut, c'est ok pour nous et en ligne.

**Comment by Cqoicebordel** [comment]
Parfait ! Merci :)
