### ISSUE TITLE
HTTPS sur la version desktop du site ?

### ISSUE THREAD

**Issue by Wenzel** [NextINpact/nxiv6#49]
Bonjour,

je viens de remarquer que [NextInpact](http://www.nextinpact.com/) ne proposait pas d'utiliser HTTPS sur la version desktop.
Même en forçant le protocole, on en revient toujours à HTTP.

En utilisant `m.nextinpact.com` par contre, on tombe bien sur un lien HTTPS.

Pourrier-vous fournir (et forcer) une version HTTPS du site ? :)

Merci !

**Comment by papci** [comment]
Bonjour,

HTTPS est déjà disponible pour l'ensemble de nos Abonnés et nous travaillons à sa généralisation qui devrait intervenir courant 2017.
