### ISSUE TITLE
Problème de login sur NXI avec un firefox "hardened"- CORS

### ISSUE THREAD

**Issue by MikeZeDev** [NextINpact/nxiv6#50]
Bonjour. Il m'est impossible de me connecter à mon compte NXI sur Firefox

Si je désactive toutes mes extensions le problème persiste.
Si je part sur un profil vierge cela fonctionne, je conclut que le problème vient d'un paramètre de sécurité activé dans mon user.js.

L'erreur donnée dans la console de Firefox est une erreur de CORS semble t'il

> 
17:41:23,130 Blocage d’une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://www.nextinpact.com/Account/Login. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. 1 (source inconnue)

Au vu de l'erreur, il s'agit peut-être d'un problème avec un paramètre 

> "security.fileuri.strict_origin_policy" à "true"

Pour référence mon user.js est situé ici https://github.com/pyllyukko/user.js/blob/master/user.js
Je l'ai bien entendu modifié pour autoriser les cookies et les polices distantes )

Etant donné que cela parle d'entête manquante, je me dit qu'il peut y avoir quelque chose à modifier sur votre site . Ou alors c'est ce paramètre qui est trop restrictif

**Comment by papci** [comment]
Vu que nous sommes passé en full HTTPS, est-ce que tu peux me dire si c'est cela se produit encore ?

Merci !

**Comment by MikeZeDev** [comment]
En effet depuis la mise à jour tout fonctionne !
Je pense que l'on peut fermer cette "issue"
