### ISSUE TITLE
www.nextinpact.com uses an invalid security certificate

### ISSUE THREAD

**Issue by Wenzel** [NextINpact/nxiv6#52]
Bonsoir,

en tentant d'accéder à vos articles via feedly, j'ai reçu aujourd'dui l'erreur HTTPS suivante :

~~~


www.nextinpact.com uses an invalid security certificate.

The certificate is only valid for the following names:
  ssl378410.cloudflaressl.com, *.baseballwarehouse.com, *.cretedoc.gr, *.pinkapple.com, *.softballrampage.com, *.undercovercondoms.co.uk, baseballwarehouse.com, cretedoc.gr, pinkapple.com, softballrampage.com, undercovercondoms.co.uk  

Error code: SSL_ERROR_BAD_CERT_DOMAIN
~~~

Les URLs des articles du flux RSS sont en `HTTPS` désormais je suppose ?
Et la mauvaise configuration du certificat à provoqué cette erreur ?

Cordialement.

**Comment by Wenzel** [comment]
![www.nextinpact.com uses an invalid security certificate](https://cloud.githubusercontent.com/assets/964610/21366391/4984b796-c702-11e6-9157-5e94f27bed84.png)

**Comment by Fabiensk** [comment]
Je ne peux également plus me connecter sur mon compte Next Inpact pour la même raison.

**Comment by Fabiensk** [comment]
Je constate que c'est rétabli.

**Comment by papci** [comment]
Un ticket de support a été établi chez notre presta, et  le problème est résolu ;)
