### ISSUE TITLE
Problème de changement de mot de passe

### ISSUE THREAD

**Issue by loconox** [NextINpact/nxiv6#53]
Je me permets de reprendre une demande que j'ai envoyé par mal.

J'ai rencontré un problème lors du changement du mot de passe de mon compte. En effet, j'ai tenté de choisir un nouveau mot de passe de 32 caractères, or cela n'a pas fonctionné. Dans un premier temps je n'ai pas compris pourquoi car le formulaire ne m'indiquait rien, ensuite j'ai remarqué que le serveur me renvoyait une erreur 500.

Améliorations possible :
- afficher un message d'erreur plus explicite en cas de problème de ce genre ;
- supprimer la limite de taille sur le mot de passe, ou la mettre une valeur bien plus grande (255 ?).

Merci d'avance.

**Comment by papci** [comment]
merci pour la remontée, nous allons augmenter la taille et préparer un message de validation.

**Comment by csu333** [comment]
J'ai rencontré la même erreur 500 avec un mot de passe contenant des caractères spéciaux (en particulier des caractères utilisés par le code HTML). 

Je dois avouer que je suis un peu inquiet car cela indique au mieux une erreur dans le code, au pire, la possibilité d'injecter du SQL ou du code HTML dans certains de vos champs. C'est bien de se protéger contre les DDoS chez CloudFlare mais ça ne protège pas des fuites de données...

**Comment by papci** [comment]
@csu333 : non, cela indique simplement une erreur. Dans notre cas, c'est justement la protection qui pose souci. Le système détecte une action dangereuse et rejette par défaut la requete et log l'exception. 
Cependant un fix arrive rapidement.

**Comment by papci** [comment]
Un fix a été déployé ce jour.

**Comment by csu333** [comment]
ça marche pour moi en effet. Merci
