### ISSUE TITLE
Bug sur firefox mobile avec Ublock origin 

### ISSUE THREAD

**Issue by oldchap32** [NextINpact/nxiv6#54]
Quand Ublock origin 1.10.4 est activé les articles sont vides quand je clique sur les liens depuis la page https://m.nextinpact.com, pas de soucis avec l'extension désactivée.

Compte abonné premium, identifiant : oldchap

Firefox Mobile version android 50.1.0
Android 5.1.1 sur nexus 4
![screenshot_2016-12-28-16-18-50](https://cloud.githubusercontent.com/assets/7286972/21524890/bdc35b22-cd19-11e6-9aae-8656404ab205.png)

**Comment by papci** [comment]
Effectivement il s'agit d'une règle d'adblock (+nextinpact.com##[style="display: none;"] + [class]), on ne peut pas fixer de notre coté, il faut qu'ils corrigent. je vais tenter de voir avec le mainteneur de la liste sur twitter (et peut-être ici @SMed79 ?)

**Comment by SMed79** [comment]
https://hg.adblockplus.org/listefr/rev/953d3d85b60d

Utiliser notre forum pour signaler https://forums.lanik.us/viewforum.php?f=91

**Comment by papci** [comment]
merci @SMed79
