### ISSUE TITLE
Images visibles dans les articles malgré préférences

### ISSUE THREAD

**Issue by oldchap32** [NextINpact/nxiv6#55]
Mes réglages sont paramétrés avec les images masquées mais celles ci apparaissent tout de même dans les articles. Sont concernées toutes les images : bannière, pictos réseaux sociaux, photo rédacteur…

Le problème a commencé fin octobre. Résultat idem sur chrome mobile et firefox mobile.
![screenshot_2016-12-28-16-25-17](https://cloud.githubusercontent.com/assets/7286972/21525095/270bd0b8-cd1b-11e6-8290-1feaa2c02e37.png)

**Comment by papci** [comment]
Le paramètre "Images" agit désormais sur l'image dédiée ainsi que sur la photo rédacteur.
