### ISSUE TITLE
Mauvaise IP flashée :)

### ISSUE THREAD

**Issue by Geolim4** [NextINpact/nxiv6#56]
Hello,

Sur la page 404 du site, exemple:
https://www.nextinpact.com/erreur-404
L'IP "flashée" est celle du proxy Cloudflare et non celle du visiteur :P

Bonne journée :)
Georges

**Comment by Geolim4** [comment]
Salut @papci du nouveau la-dessus ? :)

**Comment by papci** [comment]
Hello,
Oui un fix est prévu d'ici quelques jours ;)
Je te tiens au courant sur ce ticket.

Bon week end !

**Comment by Geolim4** [comment]
Hello, pas de soucis, bon week également !

**Comment by papci** [comment]
Nous avons restauré la vue au radar ;)

Merci pour ta contribution.

**Comment by Geolim4** [comment]
Bien joué @papci  !
