### ISSUE TITLE
Accès aux notifications

### ISSUE THREAD

**Issue by 127-001** [NextINpact/nxiv6#57]
Le compteur de notification affiche un nombre >0, mais quand je clique sur le compteur celui-ci se remet à zéro et la dropbox affiche "Vous n'avez aucune notification." 

comportement observé depuis le 29/12/2016.

https://www.nextinpact.com/SocialBar/GetCountNotification
`{"success":true,"nbNotifs":2}`

https://www.nextinpact.com/SocialBar/GetNotification
...
`<div class="bloc_no_notification">`
`<p class="sb_incrust">Vous n'avez aucune notification.</p>`
`</div>`
...

**Comment by papci** [comment]
merci pour la remontée. cc @ryuKKu-

**Comment by papci** [comment]
Un fix a été appliqué ce matin ;)

**Comment by 127-001** [comment]
Réactivité & efficacité. Bravo !
