### ISSUE TITLE
Crédits image d'illustration: pas de lien vers Wikimedia Commons

### ISSUE THREAD

**Issue by Fabiensk** [NextINpact/nxiv6#59]
Cet [article](https://www.nextinpact.com/news/102777-replay-archeologie-factice-volcans-et-animaux-geants.htm) a comme illustration une image provenant de Wikimedia Commons comme indiqué par une légende. Par contre, l'auteur n'est pas crédité dans la page (ou alors c'est bien caché), alors que la licence de l'[image](https://commons.wikimedia.org/wiki/File:Sunset_sakurajima.jpg) (Creative Commons Paternité) demande à ce qu'on crédite l'auteur, et pas le site ayant hébergé l'image.

> paternité – Vous devez citer le nom de l’auteur original de la manière indiquée par l’auteur de l’œuvre ou le titulaire des droits qui vous confère cette autorisation (mais pas d’une manière qui suggérerait qu’il vous soutienne ou approuve votre utilisation de l’œuvre).

Je suggère:

- de  mettre un lien vers la source (comme le fait Ars Technica [par exemple](http://arstechnica.com/science/2017/01/in-chemistry-computational-models-may-be-getting-worse/))
- de mettre de nom de l'auteur

**Comment by papci** [comment]
Bonjour,

Pour toutes questions et suggestions relatives à la rédaction, tu peux passer par le formulaire dédié : https://www.nextinpact.com/a-propos.htm#nouscontacter_section (choisir "poser une question à la rédaction").

**Comment by Fabiensk** [comment]
Ok, merci, c'est fait. Je pensais que c'était un cas plus récurrent, mais une recherche ne donne que 2 pages dans ce cas.
