### ISSUE TITLE
HTTPS et proxy d'entreprises

### ISSUE THREAD

**Issue by glhez** [NextINpact/nxiv6#6]
Bonjour,

J'ai constaté les deux problèmes suivants assez pénibles en entreprise quand cette dernière impose un proxy refusant le HTTPS :

- Les flux RSS HTTP (celui-là : http://www.nextinpact.com/rss/news.xml ) référencent des urls en HTTPS; ces dernières étant bloquées, cela fait un platonique "connexion refusée" sur Firefox
- Les images (exemple cette news: http://www.nextinpact.com/news/98290-redevance-copie-privee-medaille-dargent-pour-france.htm ) pointe sur un CDN en HTTPS.

L'utilisation de liens de la forme "//www.example.org" permet d'éviter ces écueils.

Cordialement,
Gaël LHEZ

**Comment by papci** [comment]
Hello,

Merci pour la remontée on va corriger ça.

**Comment by glhez** [comment]
Tant que j'y pense: y a moyen d'avoir une forme d'authentification HTTP ? En gros, je voudrais pouvoir lire mes news abonnés... sauf que le proxy bloque encore & toujours.

**Comment by papci** [comment]
Hello,

On réfléchit toujours au meilleur moyen de fournir une version non HTTPS de NXi. Pour la partie identification, c'est plus sensible car nous souhaitons réellement pousser tout le monde à faire attention à ce genre de problématique.

**Comment by glhez** [comment]
Je ferme, vu que maintenant le flux RSS renvoie vers du HTTP, que je peux même me connecter.
