### ISSUE TITLE
Mauvaise URL image dans le flux RSS

### ISSUE THREAD

**Issue by LeoColomb** [NextINpact/nxiv6#63]
![image](https://cloud.githubusercontent.com/assets/846943/22035020/adb26766-dcee-11e6-92f0-476e6202090a.png)

Dans une recherche sur le flux RSS, le problème semble apparaître à l'article [_Internet Archive lance son extension Chrome pour retrouver les pages web introuvables_](https://www.nextinpact.com/news/102888-internet-archive-extension-chrome-cherche-dans-wayback-machine-en-cas-page-introuvable.htm).

**Comment by papci** [comment]
Merci pour la remontée, un fix est déjà prévu pour ce jour ;)

**Comment by papci** [comment]
c'est corrigé ;)
