### ISSUE TITLE
Soucis sur chatbox et forum

### ISSUE THREAD

**Issue by manchettefr** [NextINpact/nxiv6#64]
Bonjour,

Quelques questions svp :

l'affichage de votre site connait t'il des problèmes ?

- Depuis peu je ne vois plus le contenu de la chatbox, juste un rond qui tourne dans le vide ; 
pas de liste des messages en cours, juste de quoi saisir la question en bas, mais je ne vois pas s'afficher ce que je valide.

- j'ai voulu poster dans le forum : créer un nouveau message -> là je ne voyais que le titre et la rubrique étiquettes, pas de quoi saisir le contenu du nouveau message.

- Rubrique "nous contacter" : envoi du message impossible.

Merci

Cordialement

Fabrice

**Comment by papci** [comment]
Bonjour,

Il s'agit de problèmes récurrents dus  à ton bloqueur de pub (les dernières maj de la liste fr ne laissent plus rien passer : https://hg.adblockplus.org/listefr/rev/10c4108afb48), la seule solution est de désactiver ton bloqueur pour Next INpact et les sites associés (forum, gestionnaire de compte etc.)
