### ISSUE TITLE
RSS flux : mauvais image affichée

### ISSUE THREAD

**Issue by pipo114** [NextINpact/nxiv6#66]
Je lis les articles de NextINpact avec Feedly grâce aux flux RSS, et depuis quelques jours, les illustrations des articles sont les portraits de nos chers rédacteurs (non pas que je ne les apprécient pas, hein....)
Par contre, lorsque je navigue sur le site site j'ai bien une illustration en relation avec l'article proposé.

Je pense que les  illustration extraite dans les RSS ne sont pas bien sélectionnées.

**Comment by papci** [comment]
c'est corrigé ;)
