### ISSUE TITLE
Liens externes

### ISSUE THREAD

**Issue by LeoColomb** [NextINpact/nxiv6#68]
Sur le site et dans le flux, il arrive _relativement_ souvent que les liens externes soient mal gérés, i.e. préfixés par `https://www.nextinpact.com/news/` :

```html
<a href="https://www.nextinpact.com/news/g30.sncf.com" target="_blank" class="ui-link">n'importe quel autre voyageur</a>
```

**Comment by papci** [comment]
Bonjour,

Pour toute demande de correction d'erreurs concernant la rédaction, tu peux passer par le formulaire de signalement d'erreur disponible sur la page de l'article en question.
