### ISSUE TITLE
Bouton "Afficher les factures" dans "Mon compte" inopérant

### ISSUE THREAD

**Issue by roadster31** [NextINpact/nxiv6#69]
Après avoir renouvelé mon abonnement, je souhaite obtenir une facture. Dans mon compte, je clique "Afficher les factures", mais il ne se passe strictement rien. Cliquer sur ce bouton ne produit aucun effet.

Indice : j'utilise uBlockOrigin

**Comment by papci** [comment]
Bonjour,

Comme tu l'a déjà signalé, il s'agit d'un problème concernant l'utilisation d'un bloqueur de pub. On ne peut rien faire de notre côté. Tu dois désactiver ton bloqueur et éventuellement signaler le souci sur le forum easylist.

bonne journée :)

**Comment by roadster31** [comment]
Je suis sûr qu'avec un peu de travail sur le contrôle des erreurs JS, ça pourrait aussi fonctionner avec un bloqueyr de pub.
