### ISSUE TITLE
Redirection bon plan et URL avec caractère '

### ISSUE THREAD

**Issue by jonag** [NextINpact/nxiv6#7]
La redirection ne fonctionne pas pour [ce bon plan](https://www.nextinpact.com/redirect-bon-plan?idBonplan=13848). 

Après vérification j'ai cette erreur dans la console Chrome
> Uncaught SyntaxError: missing ) after argument list (ligne 59)

Et cela semble se produire car l'URL vers laquelle la redirection doit se faire contient un ' ce qui produit un Javascript invalide :

```javascript
<script defer type="text/javascript">
            setTimeout(function () {
                setOut('https://store.playstation.com/#!/fr-fr/reward_game/playstation-plus-1-an-d'abonnement-25-de-remise/cid=IP9102-NPIA90006_01-PSPLUSSUBS12MDIS');
            }, 1000);
        </script>
```

**Comment by papci** [comment]
corrigé, merci ;)
