### ISSUE TITLE
Formulaire de contact non fonctionnel sur Chrome

### ISSUE THREAD

**Issue by roadster31** [NextINpact/nxiv6#70]
Sur la page https://www.nextinpact.com/a-propos.htm#nouscontacter_section, avec Chrome v55, il manque des champs de saisie :

![img-2017-01-29_17-52-26](https://cloud.githubusercontent.com/assets/2197734/22406086/2e471500-e64c-11e6-91b2-502c8f83c6e5.png)

Le bouton "Envoyer" n'a aucun effet.

Sur Firefox, les champs de saisiue sont là, mais le bouton "Envoyer" n'a aucun effet.

Indice : j'utilise AdBlockPlus pour Chrome, et uBlockOrigin pour Firefox.

**Comment by papci** [comment]
Idem que #69, il faut désactiver ton bloqueur de pub.
