### ISSUE TITLE
[Commentaires] Mauvaise URL sur bouton "VOIR TOUS LES COMMENTAIRES"

### ISSUE THREAD

**Issue by Alex131089** [NextINpact/nxiv6#72]
Si j'affiche un unique commentaire (comme https://www.nextinpact.com/news/102685-gpg-comment-creer-paire-clefs-presque-parfaite.htm#/comment/5827244)
et que je clique sur "Voir tous les commentaires", l'url dans la barre de navigation devient "https://www.nextinpact.com/#/page/4", ce qui forcément pose problème si on fait un F5 par dessus :)

**Comment by papci** [comment]
Merci pour la remontée 👍 

Note : ne se produit qu'en utilisant le mode fil de discussion.

**Comment by papci** [comment]
c'est corrigé ;)
