### ISSUE TITLE
Appliquer les préférences de thèmes sur tous les sites du groupe NextInpact

### ISSUE THREAD

**Issue by Zulgrib** [NextINpact/nxiv6#76]
Il devrait être possible d'appliquer une préférence de thème depuis la page de gestion de compte et que cela soit appliqué sur tous les sites du groupe, y compris la page compte, lidd, forum etc.

**Comment by papci** [comment]
Cette option n'est présente que sur NXi car elle n'est pertinente que pour ce site. Pour le moment, Il n'est pas prévu de déporter les thèmes sur les autres.
