### ISSUE TITLE
Répondre à plusieurs personnes dans les commentaires d'articles

### ISSUE THREAD

**Issue by Zulgrib** [NextINpact/nxiv6#78]
Actuellement, il n'est pas possible de répondre à plusieurs personnes dans un même message, il faut soit flood avec un message par réponse, soit utiliser les citations.

Pour reproduire le problème : 
- Ouvrir un article NXi qui a des commentaires
- Cliquer sur le bouton répondre d'un commentaire
- Cliquer sur le bouton répondre d'un commentaire d'une autre personne
- La réponse sera faite à l'autre personne et pas aux deux

**Comment by papci** [comment]
c'est intentionnel : "répondre" est fait pour démarrer une discussion entre deux participant. L'outil citation est à utiliser dans ce cas de figure.
