### ISSUE TITLE
Recherche sur une période donnée ne marche pas

### ISSUE THREAD

**Issue by BobQuiTue** [NextINpact/nxiv6#8]
Lorsque l'on recherche la chaîne "xcode", on trouve bien la news du 09/06/2015 à 15h33 intitulée "WWDC : tout ce qu'il faut retenir des annonces d'Apple".

Lorsque l'on précise dans les champs de période : "01/06/2015" et "15/06/2015", en laissant la chaîne "xcode" dans le champ principal, alors il n'y a aucun résultat.

Plus généralement j'ai l'impression que l'utilisation des champs "période" ne fonctionne pas, ou alors la syntaxe que j'ai utilisée ne fonctionne pas, auquel cas il serait peut-être intéressant de préciser la syntaxe attendue ?

Merci :) !

**Comment by papci** [comment]
Bonjour,

En passant par ce lien (qui correspond au filtrage que tu me donnes) : http://www.nextinpact.com/recherche?_search=xcode&RubriqueId=&Author=&OrderType=date&DateStartPeriod=2015-06-01&DateEndPeriod=2015-06-15&ListTypeContent.actus_view=true&ListTypeContent.dossiers_view=true&ListTypeContent.bonsplans_view=true&ListTypeContent.archives_view=true

j'ai bien le résultat attendu.  Pourrais-tu me donner plus détail sur l'environnement utilisé ? (OS, navigateur etc.)

**Comment by BobQuiTue** [comment]
Effectivement suivant l'environnement ça marche plus ou moins bien.

OS : OS X Yosemite 10.10.5

Navigateur :

- Safari 9.0.3 (toutes extensions désactivées)
        La requête ne marche pas : renvoie les résultats pour "xcode" quelle que soit la date.
        Le texte "xcode" est bien affiché dans le champs de recherche, mais les champs de date sont vides.
        L'url est transformée en https://www.nextinpact.com/recherche?_search=xcode&RubriqueId=&Author=&OrderType=date&DateStartPeriod=&DateEndPeriod=&ListTypeContent.actus_view=true&ListTypeContent.dossiers_view=true&ListTypeContent.bonsplans_view=true&ListTypeContent.archives_view=true
           => on voit que les startperiod et endperiod sont remplacées par du vide
       Les champs de date ne contiennent ni "jj/mm/aaaa", ni spinner ni flèche pour afficher le calendrier.


- Chrome 49.0.2623.87 (aucune extension additionnelle)
        La requête marche parfaitement.
        Le texte "xcode" est bien affiché dans le champs de recherche, et les dates sont bien affichées dans leur champ respectif.
        L'url reste inchangée.
        Les champs de date proposent un spinner, une flèche pour afficher le calendrier, et la saisie des dates marche par bloc.


- Firefox 45.0.1 (aucune extension)
        La requête marche parfaitement.
        Le texte "xcode" est bien affiché dans le champs de recherche, mais les champs de date sont vides.
        L'url est transformée en https://www.nextinpact.com/recherche?_search=xcode&RubriqueId=&Author=&OrderType=date&DateStartPeriod=&DateEndPeriod=&ListTypeContent.actus_view=true&ListTypeContent.dossiers_view=true&ListTypeContent.bonsplans_view=true&ListTypeContent.archives_view=true
           => on voit que les startperiod et endperiod sont remplacées par du vide
        Les champs de date ne contiennent ni "jj/mm/aaaa", ni spinner ni flèche pour afficher le calendrier.

**Comment by papci** [comment]
Merci pour le rapport complet.

**Comment by papci** [comment]
c'est corrigé ;)

**Comment by BobQuiTue** [comment]
Merci :) !
