### ISSUE TITLE
Mode incognito : changer de police

### ISSUE THREAD

**Issue by emersion** [NextINpact/nxiv6#81]
Les listes défilantes pour sélectionner la police de caractère et sa taille ne font rien. Pourtant, j'ai toujours rêvé de pouvoir lire un article en Comis Sans MS !

**Comment by papci** [comment]
Bonjour,

Pourrais-tu envoyer un rapport complet de configuration ? (http://supportdetails.net/) merci

**Comment by emersion** [comment]
Wow, je viens de réessayer et :
1. La sélection de la taille de la police fonctionne
2. La sélection de la police en elle-même ne fonctionne pas parce que je n'ai pas les polices installées sur mon système

Autant pour moi !
