### ISSUE TITLE
Ne pas remonter de trop vieux dossiers dans le flux RSS

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/nxiv6#82]
Actuellement les 3 derniers dossiers sont mis dans le flux RSS. Malheureusement ils datent de quelques années : 
* iPhone 6s et 6c : les 10 améliorations qu'il faut attendre => 01/04/2015
* Noël [J-7] : notre guide de survie (et de cadeaux) => 17/12/2014
* Profession : Youtubeur => 26/09/2014

Pourquoi reviennent ils systématiquement ?

**Comment by papci** [comment]
Ils reviennent parceque ce sont les derniers dossiers publiés. Cependant, on va faire des modifications assez importantes dans les prochains mois qui "regleront" le problème.

**Comment by Mimoza** [comment]
Désolé je viens de voir qu'il y a déjà un ticket d'ouvert pour cela https://github.com/NextINpact/nxiv6/issues/22
