### ISSUE TITLE
Résultat de recherche étrange

### ISSUE THREAD

**Issue by Mimoza** [NextINpact/nxiv6#85]
Bonjour,
En mettant un terme du titre de la dernière news la fonction de recherche ne remonte pas l'article.
Ex en ce moment c'est l'article du CeBIT et pourtant le premier retour de la recherche est «NVIDIA n'annonce pas de GeForce GTX 1080 Ti, mais un GeForce Now pour Mac/PC... trop cher» du 05/01/2017.

**Comment by papci** [comment]
Les news sont indexées dans notre moteur de recherche périodiquement, c'est pourquoi elle n'apparait pas immédiatement.
