### ISSUE TITLE
chrome - différents bugs d'affichage (?)

### ISSUE THREAD

**Issue by jems** [NextINpact/nxiv6#86]
environnement : RHEL 7/chrome 55

Dans le formulaire de contact, je ne vois pas les champs type de demande et adresse email.
Plus gênant, dans le formulaire d'abonnement je ne peux pas choisir le pack de goodies, je ne vois pas les choix de type et de taille, et donc ne peux soumettre le formulaire.

Je vois tous ces champs dans FF 45.7 sur le même ordinateur. 
![selection_366](https://cloud.githubusercontent.com/assets/1779197/24547520/8b0099bc-1610-11e7-86b1-5c14bf3b682a.png)
![selection_365](https://cloud.githubusercontent.com/assets/1779197/24547521/8b01957e-1610-11e7-91e4-908c8b43bd27.png)

**Comment by papci** [comment]
Salut,

Il s'agit d'un problème provoqué par l'utilisation d'un bloqueur de pub. Il  ne faut pas hésiter à le désactiver et à leur signaler le souci. merci ;)
