### ISSUE TITLE
Bug zone de liste invisible pack de goodies sur Firefox (Mac)

### ISSUE THREAD

**Issue by fraynaud33** [NextINpact/nxiv6#89]
Sur firefox 52.0.2 (64 bits) sur Mac OS X 10.11.6,
dans l'onglet abonnement pour prolonger l'abonnement, l'option goodies n'affiche pas les 2 zones de listes permettant de choisir lequel (actuellement que le tshirt) ainsi que la taille. Tout cela en mode authentifié. En mode non authentifié même problème.
Lors de la validation on a du coup l'erreur "Veuillez sélectionner un modèle de goodie".
Sur Chrome 57.0.2987.133 (64 bits) cela fonctionne correctement.
![capture d ecran 2017-04-03 a 17 03 31](https://cloud.githubusercontent.com/assets/26875828/24615876/d4d66248-188f-11e7-918f-486dbaa4f6f0.png)

**Comment by papci** [comment]
Bonjour,

Il s'agit d'un problème du à l'utilisation d'un bloqueur de publicité.

Le désactiver restaurera le selecteur.
