### ISSUE TITLE
Montant total sur les factures

### ISSUE THREAD

**Issue by loiklo** [NextINpact/nxiv6#92]
J'ai lu après qu'on pouvait remonter les bug via GitHub. Donc voilà:

Le calcul du total sur les anciennes factures est buggé.

Ex:
Facture N°8764 (16/02/2015 20:34:00)
Facture N°8763 (15/02/2013 00:00:01)
Facture N°8762 (16/10/2010 00:00:01)

En particulier ce qui est drôle c'est que la 8763 et 8764 ont exactement les mêmes "articles" et la même quantité, et les deux totaux sont différents. Et faux tous les deux au passage :)

**Comment by vser1** [comment]
J'ai le même problème. Je suis en prélèvement mensuel et j'ai indiqué de moi-même le montant que je verse à NXI (supérieur au montant de l'abonnement). La facture comprend deux lignes: le montant de l'abonnement mensuel et la remise ancienneté. Le montant total correspond au montant que j'ai choisi et ne correspond donc à rien sur la facture. De plus sur ma page de profil, le «Montant de votre prochain prélèvement » ne correspond à aucun de ces chiffres (et est faux).

**Comment by papci** [comment]
Bonjour,

Pourriez-vous contacter le support directement afin d'étudier vos cas respectifs ? https://www.nextinpact.com/a-propos.htm#nouscontacter_section (choisir "problème technique")

merci.
