### ISSUE TITLE
Images visibles malgré les réglages

### ISSUE THREAD

**Issue by oldchap32** [NextINpact/nxiv6#95]
Me revoici, le fix semble avoir sauté, les images sont de nouveau visibles dans les articles malgré les préférences comme la dernière fois : https://github.com/NextINpact/nxiv6/issues/55

testé sur opéra mini 24.0.2254.115784 et firefox mobile 52.0.2 sur android 5.1.1 nexus 4

**Comment by papci** [comment]
Hello,

Je vais me renseigner pour savoir ce qu'il s'est passé et prévoir un fix rapide.

**Comment by oldchap32** [comment]
Pour compléter l'info, cela a recommencé il y a environ 1 mois je crois

merci en tout cas

**Comment by papci** [comment]
c'est corrigé, merci pour ta patience :)

**Comment by oldchap32** [comment]
en fait pas complètement, la photo en bas d'articles et les pictos sont toujours présents mais c'est un détail, ces éléments sont rapidement en cache dans le téléphone.

en tout cas merci !

----- Mail original -----
De: "Pierre-Alain David" <notifications@github.com>
À: "NextINpact/nxiv6" <nxiv6@noreply.github.com>
Cc: "oldchap32" <oldchap.truc@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 16 Mai 2017 09:59:08
Objet: Re: [NextINpact/nxiv6] Images visibles malgré les réglages (#95)



c'est corrigé, merci pour ta patience :)
