### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by bdesmarez** [NextINpact/nxiv6#97]
bonjour,
Le formulaire de contact ne fonctionne pas
https://www.nextinpact.com/a-propos.htm#nouscontacter_section

Les deux inputs email et type de demande ne s'affichent pas, on ne peut donc pas submit le formulaire.

**Comment by papci** [comment]
Bonjour,

Il s'agit d'un problème lié  à votre bloqueur de pub, le désactiver devrait corriger le souci.
